### ISSUE TITLE
Feature Request: Automatic Config From Daily Note plugin

### ISSUE THREAD

**Issue by ScottKillen** [franciskafieh/obsidian-list-modified#10]
I'd like to suggest reading the Daily Note location from the Daily note plugin settings in much the same way that the [Periodic Notes](https://github.com/liamcain/obsidian-periodic-notes) plugin reads settings from the Calendar plugin.

This plugin obviously cannot work without the Daily Note plugin installed, so this seems like a natural feature.

**Comment by franciskafieh** [comment]
[Asked about this in the discord](https://discord.com/channels/686053708261228577/840286264964022302/960178858907295794).... waiting for a response

should be an easy feature, will release ASAP

**Comment by franciskafieh** [comment]
done! https://github.com/franciskafieh/obsidian-list-modified/commit/bbd60aeb42a2f113a9495a477e1f14180af68e62

referenced code from
https://github.com/liamcain/obsidian-daily-notes-interface/blob/502ede9670f8c1bb1e588318afe62b3e04ac5b3a/src/settings.ts#L25
