### ISSUE TITLE
[FR] Retain note metadata when it is deleted

### ISSUE THREAD

**Issue by technotherion** [franciskafieh/obsidian-list-modified#100]
List Modified 2.2.3

My format is `- [[link]] [[ctime]]`, however no ctime is embedded on my deleted notes.

This is what the plugin outputs in my weekly note. 

```## Changed Notes

### Created

- [[Philosophy]] 2024-08-17

### Modified

- [[TASK]] 2023-09-10
- [[Athena Care]] 2024-08-16
- [[Daily]] 2023-09-10
- [[Weekly]] 2023-09-10

### Deleted

- 2. Areas/Digital Stuff/This Vault.md
- 0. PeriodicNotes/2024/Weekly/Untitled.md
```

**Comment by franciskafieh** [comment]
Re-opening this. The current solution I was working on basically disables most metadata for deleted files and provides alternatives. The upcoming release will use this method for the time being.

In a future release, I plan on storing a deleted file's metadata that way things like ctime, tags, etc, can be accessed even if the file doesn't exist.

**Comment by franciskafieh** [comment]
I feel like this is out of scope for now, and the [current solution](https://github.com/franciskafieh/obsidian-list-modified/wiki/Output-Format) should be sufficient. Please feel free to re-open this issue if anyone else requires this to exist
