### ISSUE TITLE
[FR] Use Frontmatter/Properties modified and created time values (very likely out of scope)

### ISSUE THREAD

**Issue by technotherion** [franciskafieh/obsidian-list-modified#102]
I see this as likely being out of scope because if someone is writing modified and created time to their note frontmatter, then it's only a step or two away from using Dataview to give the same results that this plugin does. 

Allow for specified modified and created properties to be used instead of mtime and ctime values instead of pulling it from the file properties.  When this mode is used, only scan for changes to these specific notes' properties.

I see the ideal user for this plugin being someone who is not already using frontmatter/property fields. Thus this is totally a "cool to have" but not necessary feature. I figured I'd also give an opportunity for discussion if others want something similar.  

I am using Linter to write my Modified Time and Created Time to a note.

**Comment by franciskafieh** [comment]
Possibly an opportunity to allow using frontmatter values in general as output format. Should not be hard to implement so I will most likely add this in the next update

**Comment by franciskafieh** [comment]
Done in release [3.1.0-alpha](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/3.1.0-alpha)
