### ISSUE TITLE
[BUG] Frontmatter Properties being Blank in Output

### ISSUE THREAD

**Issue by TrulyFlawed** [franciskafieh/obsidian-list-modified#105]
## First Steps

-   [x] I've ensured that the issue **does not already exist** by [using the search feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified
-   [x] I'm on the latest release of Obsidian
-   [x] I've tried disabling any other plugins that may cause conflicts (optional but recommended)

## Describe the bug

When I use the frontmatter syntax in my output formats, they show up as completely blank in my output.

For example, I have the property, "created" and "modified". I try using the following as an output format:

`| [[link]] | [[f.created]] | [[f.modified]] |`

And all it will return is this:

`| <note link> | | |`

## Expected behavior

I would expect it would show the respective note property in the output.

### My setup

-   **What device are you on?** I am on a laptop running Windows 11
-   **What sync service are you using? (if relevant to bug)** I don't know if it's relevant here but I use Git to sync my notes.

### Steps to reproduce bug

Can you pinpoint when/why this bug happens? Please provide steps on how to reproduce this bug. A video recording is ideal. If you have some technical knowledge, please go into the Obsidian List Modified settings and turn on verbose mode. Keep the console open (ctrl/cmd + shift + i) while reproducing the bug. The messages output to console will help with debugging. Please attach these messages as a screenshot.

1. Go into settings.
2. Set output to `| [[link]] | [[f.created]] | [[f.modified]] |`.
3. Edit a note with both the `created` and `modified` properties (I set these both as the "Date & Time" property type).
4. Or create a new note with both of those properties.
5. Check log note.

## Additional info?

I'm figuring I might've just configured something wrong, or maybe it's because I've manually installed 3.1.0 and potentially screwed it up. Either way, I'm just hoping it isn't a genuine bug and just error on my part.

If you need additional info I'll try to provide it :3

**Comment by franciskafieh** [comment]
What the heck. I swear it was just working last week when I tested it! Now it's only working in test cases but not in Obsidian. I will look into it ASAP. Thanks.

**Comment by TrulyFlawed** [comment]
Apologies for not reporting this sooner btw; I looked at the commits and saw that frontmatter properties were an implemented feature, so I tried manually compiling the plugin to test them out. They didn't work for me at the time, but I figured I'd done a poor job with the compilation (since I'd never compiled Typescript before) but I guess it was a real bug.

Good luck with the fixes though, this feature is one I'm looking forward to :3

**Comment by franciskafieh** [comment]
I have fixed this issue on my local machine, but I would like to re-write a few test cases before I release it. Please remind me if it does not release within the next 24 hours :)

**Comment by TrulyFlawed** [comment]
Alright, will do.
