### ISSUE TITLE
no available settings for new format found

### ISSUE THREAD

**Issue by KriachkoAS** [franciskafieh/obsidian-list-modified#107]
no explicit setting for new list format have been found in plugin. How to start use it?

**Comment by KriachkoAS** [comment]
i maen setting that enables user to add markdown like %% modified list %% %% end %% in documents

**Comment by franciskafieh** [comment]
Oh yes, this is only in the beta version which you have to download
manually or via the BRAT plugin. Check the releases page and download the
latest pre-release. Please also read the wiki page for instructions.

**Comment by franciskafieh** [comment]
Update now that I'm on my laptop: please read here for instructions. https://github.com/franciskafieh/obsidian-list-modified/releases/tag/3.0.0-alpha

**Comment by franciskafieh** [comment]
Closing this unless you have any further questions
