### ISSUE TITLE
[BUG] Tags should only show up once

### ISSUE THREAD

**Issue by mo-seph** [franciskafieh/obsidian-list-modified#108]
If I have e.g. a task list, where tags appear many times - once for each task - then the `[[tags]]` output looks quite strange:
<img width="572" alt="image" src="https://github.com/user-attachments/assets/867ea91d-34b5-4e13-8ff5-d0cf06d61f61">

**Comment by franciskafieh** [comment]
Oh my gosh that's pretty funny. Recent update messed that up lol. I will look into it soon

**Comment by franciskafieh** [comment]
Fixed in [release 3.1.2](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/3.1.2-alpha)
