### ISSUE TITLE
[FR] Documentation Update

### ISSUE THREAD

**Issue by mo-seph** [franciskafieh/obsidian-list-modified#109]
Some documentation updates that would help:
- It's not clear what the log file is, and why I need one (or if I need one!). Is it the same as the daily note?
- I think there is some clever behaviour around detecting daily notes, but I'm not sure - is that true? If so, it would help to document
- The 'Combine Created and Modified' setting should say that they are then accessible with 'MODIFIED', but 'CREATED' will not show anything.
- The 'Auto Create Divider ...' options don't say what kind of notes they apply to - is it just daily notes?

**Comment by TrulyFlawed** [comment]
On the topic of documentation improvements, the contributor's guide could also be improved with instructions on how to compile the code.

I'm sure it could be improved in other ways but this was one of the first things I thought of when reading. (That or maybe I'm just not good at reading documentation.)
