### ISSUE TITLE
Possible more inclusive vocab than blacklist

### ISSUE THREAD

**Issue by claremacrae** [franciskafieh/obsidian-list-modified#11]
In case you are open to an alternative word to blacklist, here are some suggestions:

https://english.stackexchange.com/questions/51088/alternative-terms-to-blacklist-and-whitelist

**Comment by franciskafieh** [comment]
sorry, i had no intentions to discriminate! will probably change to 'blocklist.' does that sound good?

**Comment by claremacrae** [comment]
> sorry, i had no intentions to discriminate!

Great - I had a feeling that would be the case!

> will probably change to 'blocklist.' does that sound good?

It's definitely mentioned in multiple answers on that stack exchange question.

I slightly wonder if it's open to misreading as blacklist, with only one char different - and maybe 'blocked list' might be clearer - but don't feel that strongly. Totally up to you!

**Comment by claremacrae** [comment]
Another alternative might be to go for a more descriptive word or phrase altogether...

For example, "tags to ignore" - or "tags that will not be linked".

**Comment by franciskafieh** [comment]
> > sorry, i had no intentions to discriminate!
> 
> Great - I had a feeling that would be the case!
> 
> > will probably change to 'blocklist.' does that sound good?
> 
> It's definitely mentioned in multiple answers on that stack exchange question.
> 
> I slightly wonder if it's open to misreading as blacklist, with only one char different - and maybe 'blocked list' might be clearer - but don't feel that strongly. Totally up to you!

what about simply 'ignored tags'?

inb4 lol, just saw your message appear

**Comment by franciskafieh** [comment]
Done! See https://github.com/franciskafieh/obsidian-list-modified/commit/68df6459228128eae754f68190b430c30e16b76f and https://github.com/franciskafieh/obsidian-list-modified/commit/e3f5e1753e6f11fdb6009e623f33edd90b5b7d3f

**Comment by claremacrae** [comment]
> Done! See [68df645](https://github.com/franciskafieh/obsidian-list-modified/commit/68df6459228128eae754f68190b430c30e16b76f) and [e3f5e17](https://github.com/franciskafieh/obsidian-list-modified/commit/e3f5e1753e6f11fdb6009e623f33edd90b5b7d3f)

Wow, that was quick. Very many thanks for doing this, I really appreciate the kindness! ❤️

**Comment by claremacrae** [comment]
@franciskafieh I was curious that there were no visible UI changes, so did a search and found this:

https://github.com/franciskafieh/obsidian-list-modified/blob/master/src/settings.ts#L66

**Comment by franciskafieh** [comment]
> @franciskafieh I was curious that there were no visible UI changes, so did a search and found this:
> 
> https://github.com/franciskafieh/obsidian-list-modified/blob/master/src/settings.ts#L66
> 
> ```ts
>     .setName("Blacklisted Tags")
> ```

Argh! I missed that! let me fix right now :)

**Comment by franciskafieh** [comment]
![image](https://user-images.githubusercontent.com/93789670/161443379-3d299235-ae64-43d5-b880-25bf9f149327.png)
Nevermind, I had gotten it. Vscode/git are being weird. It isn't tracking my changes.... Going to try to fix that

**Comment by franciskafieh** [comment]
Seems like it's an issue with using git from wsl.... Just going to force git to track changes for now.

here we go! https://github.com/franciskafieh/obsidian-list-modified/commit/e08f57cc3915c9c0dac50143ffd6145c9035b204

**Comment by claremacrae** [comment]
> Seems like it's an issue with using git from wsl.... Just going to force git to track changes for now.
> 
> here we go! [e08f57c](https://github.com/franciskafieh/obsidian-list-modified/commit/e08f57cc3915c9c0dac50143ffd6145c9035b204)

That's a very weird commit. It shows every single line as changed... 

> edit: feel free to re-open the issue if i missed something else 😭

:-)
