### ISSUE TITLE
[FR] Take 3.x out of alpha

### ISSUE THREAD

**Issue by franciskafieh** [franciskafieh/obsidian-list-modified#110]
This will happen on oct 12 (2 month since 3.0.0 released) after every bug and reasonable fr is closed

**Comment by joshp12345** [comment]
I've noticed that writing any content BELOW a list is deleted when the list is updated- will this behavior be changed with the intro of the divider system?

**Comment by franciskafieh** [comment]
Yes, this is already fixed in 3.x. Feel free to download it using BRAT or
manually from the reeases page.

**Comment by joshp12345** [comment]
Great, thank you! This is a very useful plugin to have in my daily notes to backtrack through my work.

**Comment by franciskafieh** [comment]
I'm glad you find it useful :) let me know how 3.x.x is working for you, otherwise it will be released to public in the next 2 days anyway
