### ISSUE TITLE
[FR] Add percent/URL encoded file path to object format template variables 

### ISSUE THREAD

**Issue by mjknght** [franciskafieh/obsidian-list-modified#112]
## First Steps

-   [x] I've ensured that this feature request **does not already exist** by [using the search feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified

## Describe the desired feature

I would appreciate it if the output format templates included a URL encoded file path, so that I can create links using Advanced URI, rather than using standard wiki links.

**Comment by franciskafieh** [comment]
Would you be able to provide an example of how this would work? Would this only work specifically for users of the advanced URI plugin? I have never investigated the URI features

**Comment by mjknght** [comment]
Actually I suppose it would work for Obsidian links as well, though I usually use the [Advanced URI plugin](https://github.com/Vinzent03/obsidian-advanced-uri), for various reasons. In the case of List Modified, the main reason I would want to do this is so that I can link to modified files _without_ having them appearing as linked mentions, since I think this might become quite overwhelming over time. An Obsidian link would be function, but not show up – hence the request. Thanks for considering this!

**Comment by franciskafieh** [comment]
> so that I can link to modified files without having them appearing as linked mentions

would something like this suffice then?

the template `[[uri]]` gets replaced with `[Note Name](obsidian://open?vault=Vault%20Name&file=Note%20Name)`

cc: @TrulyFlawed as well

**Comment by franciskafieh** [comment]
note to self: app.getObsidianUrl(file)

**Comment by mjknght** [comment]
Yes, this would be great! Thanks for considering the request.

**Comment by franciskafieh** [comment]
Fixed here: 97cb4510875abfa56fc81a0b3d397f50fdf7b959

Will be added next release

**Comment by mjknght** [comment]
Very grateful indeed! Great addition to a great plugin.
