### ISSUE TITLE
[BUG] Notes created yesterday being added to new daily note

### ISSUE THREAD

**Issue by mjknght** [franciskafieh/obsidian-list-modified#114]
I’ve noticed that when the new daily note (with the dividers included in the template) is first created, the new notes from the previous date are added to the created list. If I manually remove them, they do not return. I wonder whether there’s a delay in clearing the JSON data from the previous day that’s causing this?

**Comment by franciskafieh** [comment]
I can reproduce this. Odd how 3.x.x produced this bug. I will look into it ASAP. Might as well also fix OLM considering previous daily note as "modified" when the plugin goes to remove the dividers

**Comment by garbosz** [comment]
+1 for me as well, the issue is also exacerbated for me having multiple computers with obsidian that sometimes dont connect for a day or two(ie work laptop off for the weekend etc)

**Comment by franciskafieh** [comment]
> or two

does this mean the last 2 days worth of created notes are moved to today? or in other words, how is it aggravated? this might help me fix it, but I have no looked into it that much yet. I am currently very busy with school.

**Comment by mjknght** [comment]
Only the previous day, for me. No more than 1. Thanks!

**Comment by garbosz** [comment]
> > or two
> 
> does this mean the last 2 days worth of created notes are moved to today? or in other words, how is it aggravated? this might help me fix it, but I have no looked into it that much yet. I am currently very busy with school.

it really depends on how the offline computer recovers from syncing the data into the local vault and whether it triggers any reindexing. but most of the time it only shows the previous day

**Comment by franciskafieh** [comment]
This seems to also happen for deleted notes.
