### ISSUE TITLE
[BUG] New list modified using the %% LIST MODIFIED %% separators doesn't do anything 

### ISSUE THREAD

**Issue by ngokevin** [franciskafieh/obsidian-list-modified#115]
## First Steps

-   [x] I've ensured that the issue **does not already exist** by [using the search feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified
-   [x] I'm on the latest release of Obsidian
-   [ ] I've tried disabling any other plugins that may cause conflicts (optional but recommended)

## Describe the bug

![image](https://github.com/user-attachments/assets/24d3c30a-42fe-41f6-95cb-357096b991e5)

I have `%% LIST MODIFIED %%` + `%% END %%` tags in my Daily Notes, but the plugin isn't doing anything when I edit notes.

![image](https://github.com/user-attachments/assets/0613e139-8fdf-45ad-9afd-05a9521cf8da)

It just stays empty no matter what

## Expected behaviour

List modified adds links to modified or created notes

### My setup

-   **What device are you on?** MacOS
-   **What sync service are you using? (if relevant to bug)** None

### Steps to reproduce bug

Before the plugin was working flawlessly. Then I updated the plugin + Obsidian. I actually had to re-install the plugin to see all the new settings options. But after reinstall + restarts, the plugin doesn't do anything to my Daily Note even with the separators.

My plugins

![image](https://github.com/user-attachments/assets/ce9e9b7c-a83a-454b-b8c6-3e5f7e9383c1)

**Comment by franciskafieh** [comment]
Have you tried enabling auto-create log note and turning on auto-create all the dividers? What happens?

**Comment by ngokevin** [comment]
It works if I have it append the dividers for me, that works for me, thanks!

**Comment by franciskafieh** [comment]
Super odd, as the code for locating the dividers (whether they are manually made or automatically appended) is exactly the same. Did you happen to upgrade recently from 2.x.x to 3.x.x? This seems to have caused random problems for many people

**Comment by ngokevin** [comment]
Yeah, I made an upgrade from 2 to 3. There were odd issues where most of the v3 settings didn't show up until I reinstalled the plugin too.

**Comment by franciskafieh** [comment]
The issue doesn't seem to happen with new installs, so I don't think there's an issue with detecting the dividers. Signs point to upgrade issue, but I still have to look into it.
