### ISSUE TITLE
[BUG] Sync confuses plugin and writes to incorrect parts of the note

### ISSUE THREAD

**Issue by garbosz** [franciskafieh/obsidian-list-modified#116]
## First Steps

-   [x] I've ensured that the issue **does not already exist** by [using the search feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified
-   [x] I'm on the latest release of Obsidian
-   [x] I've tried disabling any other plugins that may cause conflicts (optional but recommended)

## Describe the bug

sometimes list modified will get confused and overwrite other sections of the note and occasiounally deleted the dividers or duplicates them. 

## Expected behaviour

list modified lists files in the appropriate sections as files get modified. 

### My setup

-   windows 11 laptop(hp something)
-   obsidian sync core plugin

### Steps to reproduce bug

1. edit some notes to build list for plugin, 
2. let obsidian sync
3. edit some more files
4. list modified will sometimes write to the wrong spot in the file and will overwrite some other data while obsidian syncs new changes

## Additional info?
i think this is mostly because of some issues with syncing getting the plugin confused, and errors like these are why i think the plugin should have a setting to enable or disable per machine much like the git plugin
### Snippet of plugin bug
```
- /  / [# TBAs]
- /  / [# TBAs]
- 12:03 AM | [[Daily 2024-10-22]] | \#Periodic/Daily
- 10:02 PM | [[Christmas 2024]] | \#Gift-ideas

# Attachments

- 12:03 AM | [[Daily 2024-10-22]] | \#Periodic/Daily
- 10:02 PM | [[Christmas 2024]] | \#Gift-ideas
%% LIST MODIFIED %%
- 12:03 AM | [[Daily 2024-10-22]] | \#Periodic/Daily
- 10:02 PM | [[Christmas 2024]] | \#Gift-ideas
%% END %%
## Created
%% LIST CREATED %%
- 9:48 PM | [[dailyTemplate]] | \#Periodic/Daily
- 10:02 PM | [[Christmas 2024]] | \#Gift-ideas
- 9:49 PM | [[PNOV Bridge Template]] | \#AMZL/Bridges
## Created
%% LIST CREATED %%
- 9:43 PM | [[pnov Log new week template]] | \#AMZL/Templates
- 10:35 PM | [[kurt wash 2024-10-23]] | \#AMZL/Washes
- 10:35 PM | [[EOS Post 2024-10-23]] | \#AMZL/Washes
%% END %%
## Deleted
%% LIST DELETED%% 
%% END %%
```

### Snippet of what it should look like
```
- /  / [# TBAs]
- /  / [# TBAs]
# Attachments

# Changelog
## Modified
%% LIST MODIFIED %%
- 12:03 AM | [[Daily 2024-10-22]] | \#Periodic/Daily
- 10:02 PM | [[Christmas 2024]] | \#Gift-ideas
%% END %%
## Created
%% LIST CREATED %%
- 9:43 PM | [[pnov Log new week template]] | \#AMZL/Templates
- 10:35 PM | [[kurt wash 2024-10-23]] | \#AMZL/Washes
- 10:35 PM | [[EOS Post 2024-10-23]] | \#AMZL/Washes
%% END %%
## Deleted
%% LIST DELETED%% 
%% END %%
```

### Plugin settings
![{62BB9B4E-2CD5-4DF9-B177-4C652B3F6D54}](https://github.com/user-attachments/assets/a79db61b-6ffc-4d53-ac84-225a573be660)

![{6000EEA7-CF15-420E-A6BE-0C463733B0F2}](https://github.com/user-attachments/assets/0e5d4cad-47e4-43aa-b55e-9832c053a075)

**Comment by garbosz** [comment]
im not even sure what its trying to do here
![{6CF20E64-0C3A-4E7C-B620-886F1A084019}](https://github.com/user-attachments/assets/cc17a4f3-236b-4ae3-937f-a3990fbf3512)

**Comment by franciskafieh** [comment]
> i think this is mostly because of some issues with syncing getting the plugin confused, and errors like these are why i think the plugin should have a setting to enable or disable per machine much like the git plugin

Sync is most likely the issue, yes. It's a tricky subject for Obsidian plugins. Back to #103 , how did the suggested plugin (Plugin Groups) work out for you? Also, #91 should have fixed this bug.

Would you be able to add my discord (francoiss.) so we can diagnose this faster? I will respond when I have time (I'm very busy with school right now)

Worst case, I will just add the feature to disable the plugin on a device, but it seems like a hacky workaround and I'm sure there's got to be a better way.

**Comment by garbosz** [comment]
for #103 it ended up causing weird slowdowns on my work laptop(it has some weird things going on outside of obsidian) so i ended up disabling the sync active plugins option on obsidian sync and it hasnt been too too bad keeping plugins manually synced.

As for #91 that specific issue is fixed but i think what im experiencing now is a similar but different issue with syncing and the new dividers, like it loses what line a divider is on while its writing data to the note or something.

i most recently noticed that one of my notes ended up with ~20000 lines of it listing the same 7 or so files over and over again because i moved some stuff from one folder to another creating a delete and create event. It didnt cause any performance issues though and the list was accurate outside of the duplication. 

heres the note with the worst presentation of the bug
[Daily 2024-10-24.md](https://github.com/user-attachments/files/17529080/Daily.2024-10-24.md)

**Comment by franciskafieh** [comment]
Should I try adding an option to disable the plugin on a device then? Do you believe this would help? I don't really have anything else to offer because I don't use sync solutions

**Comment by Elaws** [comment]
@franciskafieh : Hi, I noticed some kind of similar behavior between my desktop and android device.

I sync my desktop (Windows 11) and mobile (Android) through Syncthing. When I modify a note on mobile, it then syncs to my desktop and that note is added in "LIST CREATED", with a wrong timecode.

I can create a new bug report if needed.

**Comment by franciskafieh** [comment]
> I sync my desktop (Windows 11) and mobile (Android) through Syncthing. When I modify a note on mobile, it then syncs to my desktop and that note may be added in "LIST CREATED" instead of "LIST MODIFIED", with a wrong timecode. This is not a repeatable behavior : sometimes the bug occur, sometimes not.

What do you mean by wrong timecode?

> I would like to exclude temporary files created by syncthing (all of them have "~syncthing" in their name), but the exclusion rule I created (with "~syncthing") is not applied.

Please open a new issue for the name exclusions not working, thanks

**Comment by garbosz** [comment]
update from me it looks like my original issue has largely been fixed with 3.2.0. 

ive been able to leave the plugin fully enabled on all three of my machines and as long as i make sure the plugin settings are the same on each machine everything works as intended. 

i still occasionally get rogue files listed in the modified heading especially when syncing a machine for the first time that day but the new debug buttons have made them easy to fix.

**Comment by Elaws** [comment]
> What do you mean by wrong timecode?

By wrong timecode, I meant the code was e.g. : 12:12 PM instead of say 8:03 AM.

That bug didn't reproduce yet (maybe because I made sure to set `isDesktopOnly` to `true` before using your plugin, and I made sure to never open the same note on both mobile and desktop at the same time), will update if needed.

**Comment by franciskafieh** [comment]
>  I made sure to set isDesktopOnly to true before using your plugin

This is a smart workaround. For now, I am still going to consider adding the option to disable the plugin on certain devices, but since everyone seems to have found a workaround for now, I will hold off on it.

I will look into your other issue ASAP
