### ISSUE TITLE
[BUG] Doesn't work possibly because of trailing whitespace

### ISSUE THREAD

**Issue by ngokevin** [franciskafieh/obsidian-list-modified#122]
## Describe the bug

List modified only works for me, if I let List Modified create the dividers automatically. But if I want to place my own dividers, it doesn't work. Thus List Modified can only append to a file for me. This was always the case. I tracked it and believe it's because when I save an Obsidian file, it adds trailing whitespace to my divider lines. But when List Modified creates it, it's somehow immune to this

### Divider I Created In My Template

![image](https://github.com/user-attachments/assets/1a54c51b-521a-4888-a3f1-fe7a1363a916)

### Auto-Created Divider

![image](https://github.com/user-attachments/assets/8e5038e9-8c12-4ef6-9de5-2c4b740e3857)

## Expected behaviour

List Modified should handle trailing whitespace when detecting dividers.

### My setup

-   **What device are you on?** MacBook
-   **What sync service are you using? (if relevant to bug)** none

**Comment by franciskafieh** [comment]
Good catch! Thank you.

**Comment by franciskafieh** [comment]
should be fixed: https://github.com/franciskafieh/obsidian-list-modified/releases/tag/3.2.3

**Comment by ngokevin** [comment]
works ty!
