### ISSUE TITLE
Poor documentation feedback

### ISSUE THREAD

**Issue by brimwats** [franciskafieh/obsidian-list-modified#15]
My Daily Notes are in 

`000 - Landing Page. Inbox. KO. Meta/Storage/Periodic Notes/Daily` format is `YYYY/MM. MMMM/YYYY-MM-DD`

the plugin says to put the daily note setting into the plugin settings with square brackets.

I've done `YYYY[/]MM[. ]MMMM[/]YYYY[-]MM[-]DD`

and got an error about correct format. 

So I did `YYYY[/]MM. MMMM[/]YYYY-MM-DD` and got the same error. 

So then I did `[/000 - Landing Page. Inbox. KO. Meta/Storage/Periodic Notes/Daily/]YYYY[/]MM[. ]MMMM[/]YYYY[-]MM[-]DD`

and got the same error

so then i did 

So then I did `[000 - Landing Page. Inbox. KO. Meta/Storage/Periodic Notes/Daily/]YYYY[/]MM[. ]MMMM[/]YYYY[-]MM[-]DD`

The last one worked. I recommend changing the description so that people know to include the filepath PLUS the day code. You could also just look up that setting like the periodic notes plugin does on first use.

**Comment by franciskafieh** [comment]
> You could also just look up that setting like the periodic notes plugin does on first use.

this is already done in the latest pre-release SEE: #10 

although i would advise against using it for now, since there are still some bugs
