### ISSUE TITLE
Feature Request: Exclude Folders

### ISSUE THREAD

**Issue by brimwats** [franciskafieh/obsidian-list-modified#16]
Just afeature request to exclude certain folders (i.e. template folder) -- haven't checked if this one has been addressed yet!

**Comment by franciskafieh** [comment]
Maybe i could get this done for 2.0 (ETA a few days)

**Comment by brimwats** [comment]
there's no rush! i like to review betas for bugs and errors and features. when you get to it you do! thanks for your labor!

**Comment by dsebastien** [comment]
It would indeed be great to be able to exclude certain folders :)

**Comment by franciskafieh** [comment]
now that there seems to be more interest, i will add this to my TODO and try to finish it ASAP

**Comment by franciskafieh** [comment]
Should be fixed in [release 1.2](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/1.2)

Please re-open this issue if there are any further problems!
