### ISSUE TITLE
Feature Request: Created & Deleted Files?

### ISSUE THREAD

**Issue by brimwats** [franciskafieh/obsidian-list-modified#18]
This may be totally out of scope, so feel free to delete, but I would love if I could also print just files that were created on a specific date into my daily notes (i.e. not modified ones.) I've been using this python script if if's of any use to you. @kometenstaub wrote it:

```
# License: MIT 
# github username: kometenstaub

# requires at least python 3.5 (perhaps even a higher version), I have tested it on 3.9.5

# put it into the vault root 
#
# for UNIX: use cron to run it on a timer
#
# for windows: task scheduler -> new task -> trigger (the time you want) 
# -> start a program (put in the full path to this script)
# for windows you need to figure out how to do it exactly yourself as I am on Linux

# try it out by hand for a couple of days to see if it runs bug-free
# and please have backups

# note: on windows this will append the note names you created today to the daily note
# on linux these will be the notes you modified today

import os
import time
import re

createdFiles : list = []

# the following three can be changed to your liking
timePattern : str = "%Y-%m-%d"
dailyNotesFolder : str = "C:/Users/br/syncthing/booxsidian/100 - Personal/Daily/"
pathForLogs : str = "C:/Users/bri/syncthing/booxsidian/000 - Inbox. KO. Meta/_Templates/creation_log.txt"

timeToday : str = time.strftime(timePattern)

    
for dirpath, dirnames, files in os.walk("C:/Users/bri/syncthing/booxsidian"):
    if ".obsidian" not in dirpath and ".git" not in dirpath:
        for file_name in files:
            if file_name.endswith(".md"):
                normalised_path = os.path.normpath(dirpath + "/" + file_name)
                fileCTime = time.localtime(os.path.getctime(normalised_path))
                localFileTime : str = time.strftime(timePattern, fileCTime)
                if timeToday == localFileTime:
                    createdFiles.append("- [[" + re.sub(r"\.md$", "", file_name) + "]]")

try:
    with open(f"{dailyNotesFolder}{timeToday}.md", "a", encoding="utf-8") as f:
        f.write("\n\nNotes created today:\n\n" + "\n".join(createdFiles))
        with open(pathForLogs, "a", encoding="utf-8") as l:
            l.write(f"Success: {timeToday}.md\n")
except OSError:
    with open(pathForLogs, "C:/Users/bri/syncthing/booxsidian", encoding="utf-8") as l:
        l.write(f"Error: {timeToday}.md\n")
```

and this bat file to go with it:

```
"C:\Python39\python.exe" "C:\Users\bri\syncthing\booxsidian\000 - Inbox. KO. Meta\_Templates\today.py"
```

**Comment by franciskafieh** [comment]
can't promise i will implement this, but if i do, it will be with #9 ....

there might be a way to check if the file was just created without using another event (currently using the cache change event, could maybe check if the previous cache doesn't exist)

**Comment by brimwats** [comment]
I don't know how this works technically, but maybe bc your plugin knows what time it currently is couldn't it just check to see if created time was ~24h? or if there is a DD match?

**Comment by chrisgrieser** [comment]
just in case this is implemented, logging files *deleted* on that day might also be useful

**Comment by TinkerSquirrel** [comment]
A 'created today' section would be lovely. I'm currently using a Dataview query to create that in my daily notes - it's more stable/accurate than the 'modified today' query I used to use, but by no means future-proof.

**Comment by franciskafieh** [comment]
This will be implemented soon :tm:.... already closed #3 which is the first step! working hard on 2.0 and I hope i can get it released today or tomorrow

**Comment by franciskafieh** [comment]
P.S. @brimwats @chrisgrieser @TinkerSquirrel, I'd love for you all to help me beta test @Triquetra [release 2.0](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.0). It's currently a pre-release, meaning you'll have to download it from BRAT or otherwise manual. I'll keep you all posted on further updated to created files in specific.

**Comment by franciskafieh** [comment]
Going to work on getting this done for 2.0 release!! Just released a new version that does not yet incude this, but I will get it done for next release.

**Comment by franciskafieh** [comment]
This seems to be trickier than expected. There's no easy create event I could hook into, although delete seems easy enough... Going to see how I can get this working.

**Comment by franciskafieh** [comment]
this should be done in release 2.1, which will release very soon after a little bit of further testing and bug fixes! Thanks for the patience, everyone!
