### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by brimwats** [franciskafieh/obsidian-list-modified#25]
When i click the plugin in obsidian plugins i get a "plugin ID mismatch" error and it does not load
![image](https://user-images.githubusercontent.com/73113656/163803132-9e1e4f8c-5ab7-47d1-b4ed-dec4d332e381.png)

**Comment by franciskafieh** [comment]
I'm an idiot! I forgot an 'i' in my manifest,json... let me fix now...
