### ISSUE TITLE
Unnecessary modification attention

### ISSUE THREAD

**Issue by trijste** [franciskafieh/obsidian-list-modified#26]
Hi thanks for developing this. Installed and noticed this issue. 

Opening iCloud synced vault on another device treats newly synced notes to that device as modified and adds them to daily note as if meaningfully modified.

**Comment by franciskafieh** [comment]
This is going to be hard to test, because I don't use iCloud. I wonder if this happens using other syncing services...

**Comment by trijste** [comment]
I do not do discord unfortunately. It never worked for me. 

Not sure about other sync methods. 

The notes are not in my daily notes already because I may not have synced for several days. When I sync (open the app on another device), all the notes newly synced create links on my daily note. 

I just delete them, but it's not ideal. 

The other issues I can fix with the tag exclusion feature, like for folder notes that auto modify for mocs.

**Comment by franciskafieh** [comment]
No problem! To be honest, sync conflicts are pretty much out of my control. All I can really do is check if a link exists. If the link does not exist on the local copy, but it exists on the cloud, I have no way to know.... I'm limited to the current (local) obsidian vault...

Either I'm not understanding, or it's an iCloud thing that I can't fix :(

I've been lurking around the Discord, and it seems that iCloud has many syncing issues with Obsidian. Have you tried anything else?

**Comment by trijste** [comment]
Yes but iCloud is working for me now. No worries. I figured it was a blanket modified file watch. Unless there's some difference in modification type that can be tracked, like modification on open or user versus system modification. Thanks for taking a look!

**Comment by franciskafieh** [comment]
Currently, the file is linked as modified when its cache changes (pretty much a second after a file is modified.) As far as i know, it isn't possible to check who/what caused this cache update :(

**Comment by franciskafieh** [comment]
Also going to close this for now... feel free to re-open if the issue still persists, and you think there might be something I could do to help :)

**Comment by trijste** [comment]
Thanks for looking into it. I used your "Ignored Tags" option to limit the issue, so thanks for building that in! The annoyance in my setup was with the combination of Folder Notes and the Zoottelkeeper Plugin.
