### ISSUE TITLE
[feature request] Allow dynamic generation of modified time format

### ISSUE THREAD

**Issue by Ravenclawer** [franciskafieh/obsidian-list-modified#27]
This is a amazing plugin that could allow incorporation of daily notes first and project note first approach, that all the modified notes could be linked to dailynotes

the current format is "- [[link]]"

this is ok,but simply add this information to dailynotes doesn't help to see the modified time of the note

so if you can add dynamic placeholder like {time} to this plugin to allow formatting like "- {time} [[link]]"

to generate link like - 9:00 [[link]]

**Comment by franciskafieh** [comment]
See: #4
