### ISSUE TITLE
FR: Create Daily Note, if it does not exist yet

### ISSUE THREAD

**Issue by chrisgrieser** [franciskafieh/obsidian-list-modified#28]
Right now, the plugin simply aborts with a Notice. However, creating daily notes would be nice, when you edit a page before your daily note was created.

**Comment by franciskafieh** [comment]
> Right now, the plugin simply aborts with a Notice. However, creating daily notes would be nice, when you edit a page before your daily note was created.

This feature is easy to implement. Will try to get it done for next minor release. should probably make it toggleable in settings...

**Comment by franciskafieh** [comment]
Whoops, totally forgot about this... will get to working on it soon! I've been busy

**Comment by franciskafieh** [comment]
Lol... nevermind! It's done, and should work properly.... that was really easy. Sorry for not getting it done earlier! Going to push a new release now

**Comment by franciskafieh** [comment]
feature added in [version 1.1.4](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/1.1.4).

Although I have not yet made it toggleable, since I feel like most people will want this feature. If anyone does not like it, lmk and I will add a toggle!
