### ISSUE TITLE
Allow for a specificiation of location of modified notes

### ISSUE THREAD

**Issue by franciskafieh** [franciskafieh/obsidian-list-modified#3]
- possibly a setting for choosing a heading, a callout, etc.

**Comment by talios** [comment]
This.  This would make this plugin even better. I'd love to see this. I see other plugins with this support so I assume they're using some form of intelligent Markdown parsing to extract section names and replace blocks.

**Comment by franciskafieh** [comment]
My idea (for 2.0) is to have two different "modes":

## Block Mode
- sort of like a dataview query block
- can place this codeblock in any position
- will be updated in real-time... e.g. if you add an ignored tag after the file is already linked, it will be removed
- this fixes #3 and discussion #30

## Log Mode
- basically, the current system where it appends to the end of file

**Comment by franciskafieh** [comment]
Done in 2.0 which will release today or tomorrow
