### ISSUE TITLE
FR: daily note suffix/prefix

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [franciskafieh/obsidian-list-modified#33]
It would be helpful to hide all links to modified files in the graph, or otherwise keep those links separate from other links to daily notes.

This would be very easy if, optionally, instead of adding the links to the daily note there were a setting to append to a "shadow" note. I.e. the plugin creates a file with the same name as the daily note, with an added prefix/suffix, so that all files matching that form can be hidden from the graph. This would also allow the daily note to cluster around files directly linking to and linked from that note, while keeping files simply modified on that date clustered to the shadow note.

**Comment by franciskafieh** [comment]
This would've been possible on the old version, before I removed the ability to choose the file where links are appended (because it confused people.)

Going to move this to the discussions and wait to see if anyone else would like this to be re-implemented and/or improved

**Comment by franciskafieh** [comment]
Current workaround in regards to the graph is to:
1. exclude daily notes from your graph altogether
2. change your output format from [[link]] to [[name]]

although both of these have downsides and do not solve the root problem if the user wants their modified list in a separate file for other reasons

**Comment by franciskafieh** [comment]
As of now, this is not within the scope of the plugin. Workarounds provided above should cover most use cases.
