### ISSUE TITLE
FR: add option for ordered or unordered list

### ISSUE THREAD

**Issue by TinkerSquirrel** [franciskafieh/obsidian-list-modified#37]
Love the plug-in so far. Would it be possible to add a toggle/option for choosing between adding modified files as an ordered or unordered list?

Don't know how hard this would be, so feel free to disregard if the effort isn't worth the tiny Quality of Life improvement this would bring 😅

**Comment by franciskafieh** [comment]
> Love the plug-in so far. Would it be possible to add a toggle/option for choosing between adding modified files as an ordered or unordered list?
> 
> Don't know how hard this would be, so feel free to disregard if the effort isn't worth the tiny Quality of Life improvement this would bring sweat_smile

do you mean unordered/ordered as in the html/md spec:
- unordered
- list

1. ordered
2. list

or do you mean it is an ordering by date, name, etc?

**Comment by TinkerSquirrel** [comment]
the first one 🙂 numbers vs bullet points.

Though now you mention it, ordering by name could be handy for some things too... 🤔

**Comment by franciskafieh** [comment]
Hey @TinkerSquirrel can you try putting "1." Instead of "-" in your output format? This will show as 1. 1. Etc... In editor mode, but in reading it should show as 123...

Hopefully this workaround will suffice.. Lmk! :)

**Comment by franciskafieh** [comment]
let me expand... sorry, was on phone and too lazy to type lol

in your output format in the list modified settings, put "1. [[link]]"

this will show as:
\1. some link
\1. some other link
\1. you get the idea....
in editor mode, but it should show as 1. some link 2. some other link 3. .... in reader mode

**Comment by franciskafieh** [comment]
If this is not a feasible solution, I can't think of a good way to solve this without reading current lines in the file.
