### ISSUE TITLE
Allow using glob pattern to exclude folders

### ISSUE THREAD

**Issue by dsebastien** [franciskafieh/obsidian-list-modified#39]
Currently, it seems that the full folder path must be provided. It would be interesting to use glob patterns, or at least a wildcard symbol at the end of a path to ignore it as well as all its children:

```
Folder 01
  Folder 01-001
    File A
  Folder 01-002
    File B
Folder 02
  File C
Folder 03
  Folder 03-001
    Folder 03-001-001
      File D
```

To exclude files A-D, I would like to be able to do write this exclusion rule: `Folder 01\**,Folder 02,Folder 03\**`

**Comment by franciskafieh** [comment]
Argh! I knew I was forgetting something... Need to change the implementation a little. It's harder than I thought it'd be... I'll try to get it done soon, but I currently have an English essay I really need to finish...

**Comment by franciskafieh** [comment]
P.S. It shouldn't need to have a wildcard (*). It should ignore all sub-folders by default, so in your example, ignoring Folder 01 should automatically ignore Folder 01-001 and Folder 01-002

**Comment by dsebastien** [comment]
Take your time, no pressure. Thanks a lot for the cool plugin! :)

**Comment by franciskafieh** [comment]
Sorry for the long wait. I was just writing something and I realized I _should_ just be able to check if the path to the file startsWith any of the ignored paths :facepalm: 

I don't know how such simple solutions fly over my head

**Comment by franciskafieh** [comment]
Also, would you mind if I use your codeblock directory structure in the README? The one I'm currently using is impossible to read... I forgot that markdown messes up whitespace formatting

**Comment by franciskafieh** [comment]
Should be fixed in [version 1.3.1](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/1.3.1). Please re-open the issue if I missed something!

**Comment by franciskafieh** [comment]
Nevermind. There's an urgent bug I need to fix. Deleting the latest release for now. Will release a new one in a little!

**Comment by franciskafieh** [comment]
Fourth time's the charm :sob: https://github.com/franciskafieh/obsidian-list-modified/releases/tag/1.3.3

**Comment by dsebastien** [comment]
Cool, thank you🙏
