### ISSUE TITLE
Make creation of Daily Note a setting

### ISSUE THREAD

**Issue by alexito4** [franciskafieh/obsidian-list-modified#41]
> Although I have not yet made it toggleable, since I feel like most people will want this feature. If anyone does not like it, lmk and I will add a toggle!
> _Originally posted by @franciskafieh in https://github.com/franciskafieh/obsidian-list-modified/issues/28#issuecomment-1126962803_

Hello! 

I've been enjoying this plugin a lot but I would love for the creation of the daily note to not be automatic. I create the daily note on the start of my working day, and for example I don't want to have daily notes for the weekend. 

Furthermore there is some weird issue I'm having where when opening on iOS (sync via iCloud) the plugin doesn't seem to deetct the daily note, even tho is there, and creates a duplicate. I endup with 3 or 4 daily notes per day 😂 

Cheers

**Comment by franciskafieh** [comment]
Fixed in [v1.3](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/1.3)
