### ISSUE TITLE
[FR] Update list of links when a file is deleted

### ISSUE THREAD

**Issue by Triquetra** [franciskafieh/obsidian-list-modified#46]
## First Steps
- [x] I've ensured that this feature request **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
- [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
- [x] I'm on the latest release of obsidian-list-modified

## Describe the desired feature
Sometimes I create or edit files that wind up getting merged into another file, split into multiple different files, or renamed. After doing so, the link to the "modified" file created with this plugin remains, now pointing to a file that does not exist. It would be preferable to have the now-dead-link removed automatically.

## Possible alternatives
- Manual deletion of dead links
- accidental creation of new blank files using dead links.

**Comment by franciskafieh** [comment]
This will be accomplished in 2.0. No ETA yet. It will take me a long time, because it's a full overhaul of the codebase. When renaming a file, Obsidian should automatically change all links to it. Does this not work for you?

**Comment by Triquetra** [comment]
Yes, the renaming works. The issue that prompted this FR was deleted files remaining in the list. Thanks.

**Comment by franciskafieh** [comment]
Fixed in 2.0. It's currently on the 2.0 branch which is not fully working. I'll merge 2.0 into master and release it when I finish working on it.

**Comment by franciskafieh** [comment]
@Triquetra Here's a link to 2.0 in case you want to give it a try! https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.0

You'll need to download it via BRAT or manually, as it is a pre-release.
