### ISSUE TITLE
[BUG] 2.0 Beta - previously created links in today's note deleted on upgrade

### ISSUE THREAD

**Issue by Triquetra** [franciskafieh/obsidian-list-modified#49]
## First Steps
- [x] I've ensured that the issue **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
- [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
- [x] I'm on the latest release of obsidian-list-modified
- [ ] I've tried disabling any other plugins that may cause conflicts (recommended)

## Describe the bug
I deactivated and uninstalled 1.3.3 and installed 2.0 via BRAT. At some point in that process (presumably on activation of 2.0), the existing list created by 1.3.3 was deleted in its entirety. It's not a huge deal if it only happens once on upgrade, but definitely something to be aware of.

## Expected behaviour
existing links created by previous version should remain in current daily note file

### My setup
- **What device are you on?** Windows 11 PC
- **What sync service are you using? (if relevant to bug) N/A

### Steps to reproduce bug
Can you pinpoint when/why this bug happens?
1.

**Comment by franciskafieh** [comment]
Thanks for the report! I'll try to make a method to copy the previous edits to a new file. It might be too much of a pain to transfer every single link over, since it's only a day's worth of links.

**Comment by franciskafieh** [comment]
Should be fixed in [2.0.1](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.0.1)

**Comment by franciskafieh** [comment]
Hold up, github is screwing me over with these releases.... lol

**Comment by Triquetra** [comment]
I'm not sure the method of your solution, but one way I would suggest would be to have the plugin read all the current links under the heading specified in the plugin and add them to the plugin's tally of files modified for the day. That would solve the issue and allow the plugin to avoid duplicates without needing to write the info to a separate file. This would make both future upgrades and Obsidian program restarts trivial because you know that for any given day the plugin will take into account whatever had already been recorded.

Just a thought.

**Comment by franciskafieh** [comment]
> I'm not sure the method of your solution, but one way I would suggest would be to have the plugin read all the current links under the heading specified in the plugin and add them to the plugin's tally of files modified for the day. That would solve the issue and allow the plugin to avoid duplicates without needing to write the info to a separate file. This would make both future upgrades and Obsidian program restarts trivial because you know that for any given day the plugin will take into account whatever had already been recorded.
> 
> Just a thought.

Now that i have a solution for 2.0 that will probably never need to change, future updates should not get rid of your listed notes. Program restarts are also not an issue as updated notes are persisted to disk. This is just a quick and dirty solution that should only apply for 1.3.3 -> 2.0

**Comment by Triquetra** [comment]
Got it. I just tried it, and it backed up my daily note. I suppose in order to keep that data, one needs to put it under a different heading in the original daily note. I tried to add the backed-up data to the original daily note under the heading watched by this plugin, but the backed-up data got deleted when I modified another note.

You will probably want to add to the documentation that data not created by this plugin under the specified heading will be deleted.

**Comment by franciskafieh** [comment]
> You will probably want to add to the documentation that data not created by this plugin under the specified heading will be deleted.

Yeah, I'm going to be moving the README to docs for 2.0 when I release it

**Comment by franciskafieh** [comment]
Also see #48

**Comment by franciskafieh** [comment]
new migration-safe method added in [release 2.0.2](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.0.2)
