### ISSUE TITLE
[BUG] Beta 2.0.1 frequent rewriting list of files modified

### ISSUE THREAD

**Issue by Triquetra** [franciskafieh/obsidian-list-modified#51]
## Describe the bug
As soon as any edit is made to a file, this version modifies the associated data.json, modifies the daily note by adding all files tracked in the data.json, then deletes all duplicates from the data.json (and, it seems, all files previously linked by 2.0). This happens so fast that it causes system slowdown and wreaks havoc on SyncThing, causing it to create a new conflict file every time both data.json and the daily note are changed.

This appears to be a regression. I don't experience this issue with 2.0

But since I noticed the writing (and subsequent deletion) of previously added links, it makes me wonder of this might be a solution to [the other  #issue](https://github.com/franciskafieh/obsidian-list-modified/issues/49#issue-1339655318). If the plugin added the pre-existing links under the specified header to the data.json, would it write new links for those files?

## Expected behaviour
chill

### My setup
- **What device are you on?** Windows 11 PC
- **What sync service are you using? SyncThing

## Additional info?
This bug was experienced when I switched to my laptop from my desktop. When doing so, I noticed that 2.0.1 deleted the entire header block, including the header specified in this plugin, as well as previously linked files under that header.

**Comment by franciskafieh** [comment]
Hadn't tested this between devices and with sync, going to check this out tomorrow when I have time

**Comment by franciskafieh** [comment]
> If the plugin added the pre-existing links under the specified header to the data.json, would it write new links for those files?
Yup! so users should no longer need to migrate. I'm wondering if I should set a delay between updates. Thing is, afaik there is no way to run code when Obsidian shuts down. Only on plugin unload (i.e. the plugin gets updated or disabled.) This is going to be a tricky one to fix

**Comment by franciskafieh** [comment]
Just asked on the Discord:
![image](https://user-images.githubusercontent.com/93789670/184917542-fcd721b6-f440-4608-840f-bcc44cdc256c.png)

Do you think this could be a fix? Asking because I've never used syncthing.... is this related to #43?

**Comment by Triquetra** [comment]
Yes, it could be related to issue 43, and adding your proposed regex exclusion would likely help. Though for 2.0.1, it seems to be more than that -- probably also the speed at which the daily note is updated. It seems that the note is updated while Syncthing is trying to sync it, creating conflicts because it's locked or after sync the file on the local computer is not the same as the one just synced.

The obsidian-git plugin has an activity delay that is user selectable. It causes git to not activate unless Obsidian has been inactive (no input) for a specified amount of time. That may be a good solution.

**Comment by franciskafieh** [comment]
Sorry for the delay. I've been pretty busy with other projects and IRL stuff recently. Hopefully I can get to this soon

**Comment by franciskafieh** [comment]
seems like even obsidian-git can't support this. https://github.com/denolehov/obsidian-git/issues/13

I guess i'll have to stick with the quit event for now. I'll also make a command to manually save.

**Comment by franciskafieh** [comment]
> Yes, it could be related to issue 43, and adding your proposed regex exclusion would likely help. Though for 2.0.1, it seems to be more than that -- probably also the speed at which the daily note is updated. It seems that the note is updated while Syncthing is trying to sync it, creating conflicts because it's locked or after sync the file on the local computer is not the same as the one just synced.
> 
> The obsidian-git plugin has an activity delay that is user selectable. It causes git to not activate unless Obsidian has been inactive (no input) for a specified amount of time. That may be a good solution.

Going to make this a contains instead of regex. Will be less confusing.

**Comment by franciskafieh** [comment]
@Triquetra both ignore words and interval saves are added in [release 2.0.2](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.0.2)
