### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JoelAnderson-UU** [franciskafieh/obsidian-list-modified#59]
## First Steps

-   [x] I've ensured that the issue **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified
-   [x] I've tried disabling any other plugins that may cause conflicts (recommended)

## Describe the bug

Could not update from 1.x to 2.0.2 so I uninstalled, and now I cannot install version 2.0.2 on Obsidian v1.0.3 running a MacBookPro  with Ventura.

**Comment by JoelAnderson-UU** [comment]
No worries!  I've backtracked to 1.3, and that's working for now.  I'll just await the 2.1 update.  I'll just need to watch that it doesn't get updated the next time I install updates on all 100 community plugins I have installed!  🫣

**Comment by MMoMM-org** [comment]
perhaps best to change the manifest again to an older version, atm you get a update message in obisidian and then the issue that you can't update the plugin.

**Comment by franciskafieh** [comment]
that's really odd, 
![image](https://user-images.githubusercontent.com/93789670/202823709-37b30072-4c6d-49ef-9132-26db0af8746c.png)
this is the latest release. I guess Obsidian doesn't update it when I delete a release. I'll have to ask in the Discord. Was planning on finishing it up today, but I was out all day. Sorry about that!

**Comment by franciskafieh** [comment]
![image](https://user-images.githubusercontent.com/93789670/202823990-51ad119f-7dd6-494e-b18d-acb42d8d7343.png)

Maybe I can force update it to latest release? I just gave it a try. Usually it takes a few minutes to update in the community store.

**Comment by franciskafieh** [comment]
Argh! I'm so sorry y'all, but I accidentally deleted the local copy of 2.1 :sob:

I'm not even joking... I was trying to test install the version from the plugin store, but I used the wrong vault and it permanently deleted my working copy of the plugin! For now, I guess I'll have to release 2.0.1 because 2.0.2 is still broken. Will be even more delays until 2.1 :((( but as long as you don't need "created today" and "deleted today" headings, 2.0.1 should suffice

**Comment by franciskafieh** [comment]
Nevermind, 2.0.2 works. Just had a problem on my end. Going to just release this, and you should be able to use it in the meantime! 2.0.2 also added an option for intervals between writes.

**Comment by franciskafieh** [comment]
[2.0.2 released here.](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.0.2) Give it a few minutes to update in Obsidian, and the issue *should* be fixed. I'm so sorry that 2.1 is taking so long! Something always seems to go wrong. Completely my fault for deleting the wrong thing and neglecting backups... but it's okay, now I have an excuse to re-write the thing

**Comment by MMoMM-org** [comment]
I know the nausea which overcomes somebody that you did something totally stupid after you figure it out..
thanks for the updates will look into it.
BTW: Obsidian will look into the manifest.json for a version which it then pulls from the releases, so to roll back to an older version you just need to put that older version into your manifest.json again. And it will also only look into the version from the main branch.
If you want to have a "beta" you can utilize BRAT and add a manifest-beta.json which a different version number, but that and the releases must still be in the main branch

**Comment by franciskafieh** [comment]
> I know the nausea which overcomes somebody that you did something totally stupid after you figure it out.. thanks for the updates will look into it. BTW: Obsidian will look into the manifest.json for a version which it then pulls from the releases, so to roll back to an older version you just need to put that older version into your manifest.json again. And it will also only look into the version from the main branch. If you want to have a "beta" you can utilize BRAT and add a manifest-beta.json which a different version number, but that and the releases must still be in the main branch

That's cool! Thanks for letting me know! 2.0.2 seems to have no bugs anyway, so I figured I'd just take it out of beta. Previously, I just had the beta under "pre-release" without its version in the mainest.json, and you could still get it from BRAT.

I had falsely believed 2.0.2 was broken because my daily note format was messed up. Enjoy for now!!
