### ISSUE TITLE
[BUG] Separate created and deleted files headings should be lower level than main

### ISSUE THREAD

**Issue by talios** [franciskafieh/obsidian-list-modified#69]
Love the new release with the addition of the option to separate created and deleted files.

However, it currently creates things like:

```
## Modified Today

## Created
```

which should probably be:

```
## Modified Today

### Created
```

placing the sub headings, as - well, sub headings.

**Comment by franciskafieh** [comment]
You're not the only one that wants this. For now, I will make this the default. Going to make a quick fix and I'll push it ASAP.

**Comment by franciskafieh** [comment]
Released in [2.1.1](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.1.1). Please read the released notes before updating.

**Comment by talios** [comment]
Awesome - interesting, I see however ignored tags don't seem to work anymore...  Will do some more testing on that and raise it as a separate issue if needed.

**Comment by franciskafieh** [comment]
> Awesome - interesting, I see however ignored tags don't seem to work anymore... Will do some more testing on that and raise it as a separate issue if needed.

yes, please go ahead and open a new issue if this is still a problem
