### ISSUE TITLE
[BUG] Constant New Day ... and resetting.. message and files are not linked

### ISSUE THREAD

**Issue by MMoMM-org** [franciskafieh/obsidian-list-modified#70]
Just updated to 2.1
Restarted computer and had Daily and Periodic Note Plugin enabled, Daily Notes are handled by the Periodic Notes Plugin.

Getting the following messages all the time I edit a note, but the modified note is not added to my daily note.
I did disable the daily notes plugin, and restarted. No change.
I disabled and enabled List Modified. no change.

![2023-02-14 11-18-14 - 5J-2023-02-14 - Privat - Obsidian v1 0 0 ](https://user-images.githubusercontent.com/115642933/218707348-73254fa7-e1a1-4b2d-af5b-d7bbc3fe2272.png)

**Comment by franciskafieh** [comment]
> Just updated to 2.1 Restarted computer and had Daily and Periodic Note Plugin enabled, Daily Notes are handled by the Periodic Notes Plugin.
> 
> Getting the following messages all the time I edit a note, but the modified note is not added to my daily note. I did disable the daily notes plugin, and restarted. No change. I disabled and enabled List Modified. no change.
> 
> ![2023-02-14 11-18-14 - 5J-2023-02-14 - Privat - Obsidian v1 0 0 ](https://user-images.githubusercontent.com/115642933/218707348-73254fa7-e1a1-4b2d-af5b-d7bbc3fe2272.png)

Can you please let me if you receive any warnings or errors in the console? Also please send your data.json in obsidian-list-modified's folder

**Comment by MMoMM-org** [comment]
![2023-02-14 13-50-34 - 2023-02-14 - Privat - Obsidian v1 0 0 ](https://user-images.githubusercontent.com/115642933/218744040-d11accbf-8ace-4601-8788-0a26e329674b.png)

{
  "tags": "#type/timeline",
  "excludedFolders": "100 Inbox",
  "ignoredNameContains": "Workbench",
  "outputFormat": "- [[link]]",
  "appendSpaceAfterHeadings": false,
  "autoCreateLogNote": false,
  "logNoteType": "daily",
  "writeInterval": 30,
  "autoCreatePrimaryHeading": false,
  "primaryHeading": "Notes Modified Today",
  "modifiedHeading": "Modified",
  "separateCreated": false,
  "createdHeading": "Created",
  "separateDeleted": false,
  "deletedHeading": "Deleted",
  "lastTrackedDate": "2023-02-13",
  "trackedFiles": [
    {
      "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-13.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/201 Daily/2023-02-06.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/201 Daily/2023-02-07.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/201 Daily/2023-02-08.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/201 Daily/2023-02-09.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/201 Daily/2023-02-10.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/202 Weekly/2023-W05.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/203 Monthly/2023-02.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-06.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-07.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-08.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-09.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-10.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "900 Support/920 Konfiguration/921 Hierarchie/9223 MOC.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/201 Daily/2023-02-11.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-11.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/201 Daily/2023-02-12.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-12.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "001 Yesterday.md",
      "supposedList": "modified",
      "matchesCriteria": true
    },
    {
      "path": "900 Support/930 Templater/2023-W06.md",
      "supposedList": "deleted",
      "matchesCriteria": true
    },
    {
      "path": "998 Temp/2023-W06",
      "supposedList": "created",
      "matchesCriteria": false
    },
    {
      "path": "200 Journaling/201 Daily/2023-06-01.md",
      "supposedList": "deleted",
      "matchesCriteria": true
    },
    {
      "path": "500 Verantwortlichkeiten/531 PKM/5311 LYT/! LYT 10 - Super Session 2.md",
      "matchesCriteria": true,
      "supposedList": "modified"
    },
    {
      "path": "500 Verantwortlichkeiten/531 PKM/5311 LYT/LYT 10 - Processing (Kanban).md",
      "matchesCriteria": true,
      "supposedList": "modified"
    },
    {
      "path": "500 Verantwortlichkeiten/531 PKM/5311 LYT/! LYT 10 - Sensemaking Session 2.md",
      "supposedList": "created",
      "matchesCriteria": true
    },
    {
      "path": "300 Planner/DP-2023-02-14.md",
      "supposedList": "created",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/203 Monthly/2023-06.md",
      "supposedList": "deleted",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/2023.md",
      "matchesCriteria": true,
      "supposedList": "modified"
    },
    {
      "path": "200 Journaling/202 Weekly/2023-W06.md",
      "supposedList": "created",
      "matchesCriteria": true
    },
    {
      "path": "998 Temp/Hemmingway Bridge.md",
      "supposedList": "deleted",
      "matchesCriteria": true
    },
    {
      "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-14.md",
      "supposedList": "created",
      "matchesCriteria": false
    }
  ],
  "automaticallyCreateDailyNote": null,
  "heading": null
}

**Comment by franciskafieh** [comment]
> ![2023-02-14 13-50-34 - 2023-02-14 - Privat - Obsidian v1 0 0 ](https://user-images.githubusercontent.com/115642933/218744040-d11accbf-8ace-4601-8788-0a26e329674b.png)
> 
> { "tags": "#type/timeline", "excludedFolders": "100 Inbox", "ignoredNameContains": "Workbench", "outputFormat": "- [[link]]", "appendSpaceAfterHeadings": false, "autoCreateLogNote": false, "logNoteType": "daily", "writeInterval": 30, "autoCreatePrimaryHeading": false, "primaryHeading": "Notes Modified Today", "modifiedHeading": "Modified", "separateCreated": false, "createdHeading": "Created", "separateDeleted": false, "deletedHeading": "Deleted", "lastTrackedDate": "2023-02-13", "trackedFiles": [ { "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-13.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/201 Daily/2023-02-06.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/201 Daily/2023-02-07.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/201 Daily/2023-02-08.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/201 Daily/2023-02-09.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/201 Daily/2023-02-10.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/202 Weekly/2023-W05.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/203 Monthly/2023-02.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-06.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-07.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-08.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-09.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-10.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "900 Support/920 Konfiguration/921 Hierarchie/9223 MOC.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/201 Daily/2023-02-11.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-11.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/201 Daily/2023-02-12.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-12.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "001 Yesterday.md", "supposedList": "modified", "matchesCriteria": true }, { "path": "900 Support/930 Templater/2023-W06.md", "supposedList": "deleted", "matchesCriteria": true }, { "path": "998 Temp/2023-W06", "supposedList": "created", "matchesCriteria": false }, { "path": "200 Journaling/201 Daily/2023-06-01.md", "supposedList": "deleted", "matchesCriteria": true }, { "path": "500 Verantwortlichkeiten/531 PKM/5311 LYT/! LYT 10 - Super Session 2.md", "matchesCriteria": true, "supposedList": "modified" }, { "path": "500 Verantwortlichkeiten/531 PKM/5311 LYT/LYT 10 - Processing (Kanban).md", "matchesCriteria": true, "supposedList": "modified" }, { "path": "500 Verantwortlichkeiten/531 PKM/5311 LYT/! LYT 10 - Sensemaking Session 2.md", "supposedList": "created", "matchesCriteria": true }, { "path": "300 Planner/DP-2023-02-14.md", "supposedList": "created", "matchesCriteria": true }, { "path": "200 Journaling/203 Monthly/2023-06.md", "supposedList": "deleted", "matchesCriteria": true }, { "path": "200 Journaling/2023.md", "matchesCriteria": true, "supposedList": "modified" }, { "path": "200 Journaling/202 Weekly/2023-W06.md", "supposedList": "created", "matchesCriteria": true }, { "path": "998 Temp/Hemmingway Bridge.md", "supposedList": "deleted", "matchesCriteria": true }, { "path": "200 Journaling/205 5 Jahresjournal/5J-2023-02-14.md", "supposedList": "created", "matchesCriteria": false } ], "automaticallyCreateDailyNote": null, "heading": null }

Please update your obsidian. app.vault.process was newly added.

**Comment by MMoMM-org** [comment]
that was the issue.. thanks.
