### ISSUE TITLE
[BUG] Ignored tags not ignored

### ISSUE THREAD

**Issue by jfgrtsn** [franciskafieh/obsidian-list-modified#72]
## First Steps

-   [x] I've ensured that the issue **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified
-   [ ] I've tried disabling any other plugins that may cause conflicts (recommended)

## Describe the bug

2.1.1 doesn't ignore notes with the ignored tags.

## Expected behaviour

Notes with tags listed under ignored tags should not be listed.

### My setup

-   Mac

### Steps to reproduce bug

Can you pinpoint when/why this bug happens?

1. Modify a note that has one of the ignored tags and see it added to the list

**Comment by franciskafieh** [comment]
Fixed in release [2.1.2](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.1.2)
