### ISSUE TITLE
[FR] Make ### Modified header optional

### ISSUE THREAD

**Issue by jfgrtsn** [franciskafieh/obsidian-list-modified#73]
## First Steps

-   [x] I've ensured that this feature request **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified

## Describe the desired feature

Current behavior is to create a Modified section (H3) below the Primary Heading and list modified notes under that heading. I would like the option to suppress that sub-header and just list all created/modified notes under the main heading. There are on/off switches for Created and Deleted sections, but not for Modified.

## Possible alternatives

I tried setting the Modified heading name to blank, but it still creates a line with just "### " (blank H3).

## Additional info?

I understand you're trying to make the plugin flexible, but please make sure it can still handle the basics. What I'm going for is simple:

```
## Touched

- Note 1
- Note 2
```

**Comment by franciskafieh** [comment]
merged into #54
