### ISSUE TITLE
[FR] Create labels only when files exist under it

### ISSUE THREAD

**Issue by nununo** [franciskafieh/obsidian-list-modified#74]
## First Steps

-   [x] I've ensured that this feature request **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified

## Describe the desired feature

Now that the files are divided into created/modified/deleted (which is great btw thanks!), only create each of these headers if there are files to be listed.

In days in which I didn't delete any file I don't need the "Deleted" header.

## Possible alternatives

Delete those manually.

**Comment by franciskafieh** [comment]
Fixed in release [2.1.2](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.1.2)
