### ISSUE TITLE
[FR] Deleted Section without Links

### ISSUE THREAD

**Issue by MMoMM-org** [franciskafieh/obsidian-list-modified#75]
I would like to know which notes I deleted, but I don't want them as Links.. I don't want to pollute the suggester with those not existing note.

An option to turn this on / off would be probably the best.

**Comment by franciskafieh** [comment]
the deleted section currently does not work with links... or wdym?

**Comment by MMoMM-org** [comment]
hmm so I probably try that feature first before asking for feature request? 😞
let me check..

**Comment by franciskafieh** [comment]
currently no formatting options for deleted notes as they do not have any metadata stored with them when they are deleted

**Comment by MMoMM-org** [comment]
forget my FR it is working like I wanted.. sigh.. should tried the feature first I guess 😀
