### ISSUE TITLE
[BUG] Ignore Criterias are ignored

### ISSUE THREAD

**Issue by MMoMM-org** [franciskafieh/obsidian-list-modified#76]
I ignore:
- Tag:  type/timeline
- Folder: Folder
- Name: Workbench

Haven't tested the Folder part but notes with the tag and the Workbench note are added to the list of modified files.

**Comment by franciskafieh** [comment]
argh! just fixed this for ignored tags in 2.1.2, but I forgot to do the same fix for the other criteria. Will release in 2.1.3 lol

**Comment by talios** [comment]
I was just about to raise a ticket about folder ignores not being ignored - pulled in my Twitter export into Obsidian, and blamo - several thousand files added - ignore folder doesn't seem to work.

Will raise as another ticket.

**Comment by franciskafieh** [comment]
hey @talios, have you tried updating to 2.1.3 (latest)? This should have fixed it (I tested the folder exclude, as well as all the others)

**Comment by talios** [comment]
@franciskafieh Yep - on 2.1.3 - I'd checked that before hand when I saw this ticket was flagged merged/released.

**Comment by talios** [comment]
Unrelated note: I note the plugin isn't git-aware/doesn't understand git branches - which isn't really a fault of the plugin since Obsidian-Git, or git usage isn't a core thing.

**Comment by franciskafieh** [comment]
> @franciskafieh Yep - on 2.1.3 - I'd checked that before hand when I saw this ticket was flagged merged/released.

just tested wtith your exact folder struture (see screenshot), and it seems to be working fine. Are there any errors or warnings in your console? Can you send your data.json?

**Comment by talios** [comment]
Attached.

**Comment by talios** [comment]
I suspect - because I'd _already_ had modifications listed in the `"trackedFiles": [...]` array, that's why I'm still seeing them appear.

After quitting obsidian, pruning that back to just `[]` - restarting Obsidian everything was good.

I wonder if it'd be a good idea to prune that list if you edit/change the ignored folder list?

**Comment by franciskafieh** [comment]
> I suspect - because I'd _already_ had modifications listed in the `"trackedFiles": [...]` array, that's why I'm still seeing them appear.
> 
> After quitting obsidian, pruning that back to just `[]` - restarting Obsidian everything was good.
> 
> I wonder if it'd be a good idea to prune that list if you edit/change the ignored folder list? That may just be overkill tho, given there's a workaround.

Oh, whoops! Currently, the plugin only matches criteria on file cache change (e.g. when you modify the file.) If you pasted your twitter settings before modifying the file, then yeah, they wouldn't have been matched. Going to open a new FR to implement a criteria matcher every time a criteria setting is changed.

**Comment by fredcallaway** [comment]
I think I have this same issue, but folders are still not being ignored even after restart. Is it the case that once tracked a file will always be tracked? It would be good to add a note to the wiki about this

**Comment by franciskafieh** [comment]
> I think I have this same issue, but folders are still not being ignored even after restart. Is it the case that once tracked a file will always be tracked? It would be good to add a note to the wiki about this

I should probably get to implementing this FR, but to make sure this is actually your problem, can you provide me more details?

Does it work (i.e. not track the note) if you add the desired folder to your ignored list and then try to create a note in that folder?

**Comment by fredcallaway** [comment]
Hmm... I'm actually not able to reproduce the original problem now. It seems that the ignore list is always being respected. 🤷‍♂️

**Comment by franciskafieh** [comment]
Chances are, your issue is actually related to #78 , but since it is a new day, your tracked files list has been reset (so now all new notes respect your ignored folder config)

**Comment by fredcallaway** [comment]
I should have said: I cleared the ignore list and tried to recreate the issue starting from scratch (i.e. I let a note get tracked, then added its folder to the ignore list) but didn't encounter the same behavior as the first time—no idea what changed!
