### ISSUE TITLE
[BUG] Ignore Folder settings appear to be ignored

### ISSUE THREAD

**Issue by talios** [franciskafieh/obsidian-list-modified#77]
Similar to #76 - it looks like ignored folder settings are being ignored.

## Describe the bug

I just pulled in my Twitter export into Obsidian (markdown converted), several thousand files added to my daily note. When updating the folder settings to ignore `100 Personal/150 Social Media/Twitter Export` - the file entries continue to be picked up.

## Expected behaviour

I expect the excluded folders to not be inserted into the daily note.

**Comment by franciskafieh** [comment]
no need to open a new issue, merging back into #76 as it is the same principle
