### ISSUE TITLE
[FR] Suggestions

### ISSUE THREAD

**Issue by MartinP7r** [franciskafieh/obsidian-list-modified#80]
Sorry for the unsorted list, but here are some thoughts I had while looking at your plugin:

### 1. Primary Heading is a `##`. This should be editable (and the level of secondary headings should account for it).

E.g. it should be possible to have the primary heading as a `#` H1 heading.

### 2. There's no option to set where (folder) to automatically create the daily note or which note to use for log (name might be different).

E.g. it might be useful to embed the note as a separate note, especially because of the current behavior of `3.` below.

### 3. If there's another heading after the `Changed Notes` heading, it will be deleted every time there's a change. Headings on the same level as the primary heading should not be touched...

**Comment by franciskafieh** [comment]
1. is already requested in FR #71

**Comment by franciskafieh** [comment]
Going to close this and open a new issue for 3. Currently, it removes the next h1 but not h2. See #81
