### ISSUE TITLE
[BUG]  h1 heading after modified notes heading removed

### ISSUE THREAD

**Issue by franciskafieh** [franciskafieh/obsidian-list-modified#81]
> If there's another heading after the Changed Notes heading, it will be deleted every time there's a change. Headings on the same level as the primary heading should not be touched...

@MartinP7r

## WORKAROUND
h2 after this is not removed, so for now, you should be able to add an empty h2 after your section to block further things from being removed. This needs to be fixed ASAP anyway

**Comment by franciskafieh** [comment]
Should be fixed by [release 2.2.3](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.2.3)

**Comment by franciskafieh** [comment]
Nevermind, one second

**Comment by franciskafieh** [comment]
Right now it works so that any h1 or h2 after the modified list will not be touched. h3s will be, but I'd assume not many people would want more h3s afterwards anyway. If you do, please re-open this issue

**Comment by joellti** [comment]
@franciskafieh I have another h2 heading right after the h2 used by this plugin and my h2 gets deleted intermittently. My observation is that the accidental deletion happens when there was extended idling time before new editing starts. That's why I say it's intermittent. Let me know if you want me collect additional data to help narrow down the root cause. Thanks.

**Comment by franciskafieh** [comment]
> @franciskafieh I have another h2 heading right after the h2 used by this plugin and my h2 gets deleted intermittently. My observation is that the accidental deletion happens when there was extended idling time before new editing starts. That's why I say it's intermittent. Let me know if you want me collect additional data to help narrow down the root cause. Thanks.

I cannot reproduce this atm. I wait about 10 minutes and the header still does not get deleted. Could you:
1. Make sure you're on the latest version of OLM
2. Enable verbose mode in the plugin's settings
3. Screen record the terminal output and your daily notes file as your h2 gets deleted

Thank you

**Comment by joellti** [comment]
Sure I will do as you suggested when I can consistently reproduce it. It hasn't happened since I last reported but I will continue keeping an eye on it. And yes I am on the latest version (v2.2.3) of OLM.

**Comment by franciskafieh** [comment]
No problem. Feel free to open a new issue if it happens again.
