### ISSUE TITLE
change end of date from midnight to another time[FR] 

### ISSUE THREAD

**Issue by guihasparyk** [franciskafieh/obsidian-list-modified#82]
## First Steps

-  [x] I've ensured that this feature request **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified

## Describing the desired feature

**End of day time**
Determine today's date, if the value is 03:00 and the current date-time is 2023-03-03 02:59, then the date for today is 2023-03-02.
So the plugin add changes to the correct daily note.

## Possible alternatives

Going to bed earlier... It didn't seem to be a hassle at first, but, at the end impossible to maintain the habit. 

## Additional info?

The plugin Daily Note Opener has this feature but for opening the note, maybe merging a part of their code?

**Comment by franciskafieh** [comment]
Closing for now as wontfix. Please reopen and react to the original post if this feature is desired. If there is enough people who would like this, I will add it. The plugin is always open to PRs after 3.0 is released and the "jest" branch is merged into "master" if anyone wants to develop this feature themselves.
