### ISSUE TITLE
[BUG] Obsidian freezes when thousands of files were modified today

### ISSUE THREAD

**Issue by nununo** [franciskafieh/obsidian-list-modified#83]
## First Steps

-   [X] I've ensured that the issue **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [X] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [X] I'm on the latest release of obsidian-list-modified
-   [X] I've tried disabling any other plugins that may cause conflicts (recommended)

## Describe the bug

If thousands of files are modified today, Obsidian will freeze for a long time (sometimes forever?) some seconds or minutes after a modification is done on a note.: the keyboard no longer works and the mouse can scroll but cannot click.

## Expected behaviour

No freeze.

### My setup

-   macOS Ventura 13.3.1
-   Obsidian Sync (but then same happened with iCloud actually)

### Steps to reproduce bug

I created a new vault as copy of another one (since I was migrating from Obsidian Sync to iCloud). The vault has over 5k notes. All of the notes were considered modified and the list written to my daily note included every single one of them.

## Additional info?

I disabled every plugin except this one to make sure no other plugins were confounding its behaviour. Also, if this plugin is disabled, the problem doesn't happen, regardless of what other plugins are active.

**Comment by nununo** [comment]
I just rewrote the whole bug to reflect my new conclusions. Since the original text was misleading.

**Comment by nununo** [comment]
As a workaround I guess I will remember to disable this plugin for 24h when migrating large vaults.

**Comment by franciskafieh** [comment]
Going to look into this. Might be impossible to fix as writing 5000 lines to a file needs processing power. But maybe there is a way to do it all in the background?

**Comment by franciskafieh** [comment]
To be honest, I don't think there is a way to do this in the background. Since it only happens when migrating sync solutions, it's not a super big priority right now. If you would like to add on to this, or if someone else has the same issue, please reopen.

In that case, I would probably have to add a small delay after each file modification to check how many files are enqueued to be added to the daily note. If there's a lot (probably >~50), assume it's a sync thing and don't write to the file.
