### ISSUE TITLE
[FR] Deactivate plugin on selected devices

### ISSUE THREAD

**Issue by tophee** [franciskafieh/obsidian-list-modified#84]
## First Steps

-   [x] I've ensured that this feature request **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified

## Describe the desired feature
I had to uninstall the plugin because it was misbehaving. I tried to turn it off, but it somehow kept turning itself back on, probably via iCloud sync or something. 

I wanted to turn it off because whenever I use a device where I havenät used Obsidian for a while, the plugin would generate a huge list of modified files (also because of sync, I suppose). 

I was trying to accept these lists as "better than no lists at all" but more recently, the plugin also started to create lots and lots of conflicting versions of my daily notes. I'm not sure what was going on, but after I had to look through dozens of conflicting versions of my daily notes to find the one where I actually had my notes (not just modified and created files from the plugin), I could no longer deal with it. So that's when I turned it off, in order to be able to get on with my work. A few minutes later, it was on again. I figured it had to do with Obsidian still being open on my iPhone and iPad, so I killed Obsidian on both devices and turned it off on desktop again. It still turned itself back on and I realized that my Macbook (which I wasn't using at that time, but it was probably still connected to the internet) may also have Obsidian open, but I didn't want to continue trying to turn off the plugin, so I just uninstalled it.

It's a pity, but it just doesn't work with sync over iCloud. 

Since the plugin seems to work well, otherwise, I wonder whether it would be possible to add a setting that deactivates it on certain devices (or that activates it only on specific devices). I would then use the plugin on my desktop, but not on my other devices and would expect the problems related to sync to be gone.

Please provide a clear description of the feature.
Not sure what the best way to implement this would be but I'd imagine a setting that says "disable on this device" or something like that and when you turn that on, it would be as if the plugin wasn't installed on that device, i.e. it would do nothing.

## Possible alternatives

I tried to find a feature in Obsidian that allows turning plugins on or off on specific devices, but couldnät find anything like that...

**Comment by franciskafieh** [comment]
No simple way for me to do this from the plugin. There are some other options here you might want to try: https://www.reddit.com/r/ObsidianMD/comments/tf0nj5/disabling_plugins_on_mobile_while_keeping_them/
