### ISSUE TITLE
[FR] Change the target folder of the plugin from the Daily Notes folder to another folder

### ISSUE THREAD

**Issue by qpinex** [franciskafieh/obsidian-list-modified#85]
I realized that if this plugin works in my daily notes, it creates a chaos in my graph. Especially when I modify a lot of files a day, then when I go into the graph, I see that each one now has a link to today's daily note. And it's a scary picture. Definitely I would add my daily notes folder to the list of folders the graph ignores, but it's important to me to see the daily notes and my own links from them on the graph. 

So with templater I created a template that every time I create a daily note, creates a file in a different folder with the same name (with the date in the name). All that remains is to allow this plugin to use the new folder instead of the daily notes folder. Is it possible to do this? If not, it would be great to add this function.

**Comment by franciskafieh** [comment]
this would be possible with #33. See workarounds in that issue for now. Merging this into there.
