### ISSUE TITLE
[BUG]  Appending to wrong note

### ISSUE THREAD

**Issue by joh6nn** [franciskafieh/obsidian-list-modified#87]
## First Steps

-   [x] I've ensured that the issue **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified
-   [ ] I've tried disabling any other plugins that may cause conflicts (recommended)
    - I don't know what other plugins might conflict, but I would be glad to try disabling them

## Describe the bug

Links are consistently added to the incorrect note. I've got a vault with the following structure:
```
|-Entries
| \- [...Several Years of Daily Notes with the folder structure below]
| \- 2023
|    \ - 10 Oct
|        |- [Daily notes for Oct]
|        |- 18.md
|-Notes
|-Templates
```

Today, I enabled List Modified, with the following settings:

Instead of appending the links to the Notes heading in file Entries/2023/10 Oct/18.md , the links are being appended to Entries/2021/09 Sep/18.md

## Expected behaviour

What should happen instead?

links should be appended to the Notes heading in file Entries/2023/10 Oct/18.md

### My setup

-   **Devices**
    - Kubuntu 22.04
    - Android 12
    - Obsidian 14.16 (on both devices)
-   **What sync service are you using? (if relevant to bug)**
    - SyncThing

![image](https://github.com/franciskafieh/obsidian-list-modified/assets/1129329/dc7f256d-4c8c-4f96-a878-e82798f4c774)

### Steps to reproduce bug

Can you pinpoint when/why this bug happens?

n/a

**Comment by franciskafieh** [comment]
Could you please send me your output file configuration? Basically, just the rest of your settings pane works.

**Comment by joh6nn** [comment]
![image](https://github.com/franciskafieh/obsidian-list-modified/assets/1129329/4e399d06-dd2e-4c05-aa23-d8a5053fe313)

Ignored Tags is empty.

If you need anything else, just let me know :slightly_smiling_face:

**Comment by franciskafieh** [comment]
Would you mind sending me this part?

![image](https://github.com/franciskafieh/obsidian-list-modified/assets/93789670/6f45332d-ccd9-44f5-966c-113bcb1e5bee)

**Comment by franciskafieh** [comment]
You’re right, my bad.

**Comment by franciskafieh** [comment]
Sorry, misclick on mobile, lol. I’ll take a look in a few hours

**Comment by franciskafieh** [comment]
Alright, last thing: your Daily Notes settings pane, or your Periodic Notes settings if using that plugin

**Comment by joh6nn** [comment]
![image](https://github.com/franciskafieh/obsidian-list-modified/assets/1129329/63e3c990-485d-45b4-8478-94310588a9f9)

**Comment by joh6nn** [comment]
I do have a bunch of plugins, and I'm more than open to the idea that one or more of them is conflicting, I just don't know which one(s), or how to go about figuring that out (short of very tediously disabling all of them, and then turning them on one at a time. Which I'd love to not have to do)

**Comment by franciskafieh** [comment]
![image](https://github.com/franciskafieh/obsidian-list-modified/assets/93789670/bb07a565-e518-44e8-b677-0d1a1578630d)
I mirrored your daily notes and file name settings here exactly, and everything works fine for me. Could you do the following for me?

1. open the developer console (ctrl/cmd + shift + i)
2. type `clear()` in the prompt area at the bottom
3. screenshot the output (any errors, warnings, etc, should display)

**Comment by joh6nn** [comment]
![image](https://github.com/franciskafieh/obsidian-list-modified/assets/1129329/abcc72d4-63bf-4a50-80ac-a978c2b39b33)

I checked to see if there's any additional info if I bump the console output up to Verbose, but there's not, just the Obsidian Git plugin spamming the console with "task complete" messages.

**Comment by franciskafieh** [comment]
I think I’m going to add a debug mode to the plugin. I’ve been meaning to make one for awhile now. I’ll try to get it out tomorrow and we’ll see if it helps. In the mean time, you could try a different vault with just Obsidian List Modified, maybe? If it works there and not in your normal vault, it’s most likely a conflicting plugin

**Comment by joh6nn** [comment]
Ok, so current situation is super weird:

I tried disabling plugins in this vault in a binary search (ie, I disabled half of them and tested, then disabled half of what was left and tested, and so on), and got down to the only plugin still enabled is List Modified, and I'm still seeing the incorrect behavior.

So I created a new vault, enabled Daily Notes, installed List Modified, and tried to recreate the issue by creating a note for today (2023-10-22), and also creating a note for 2021-09-22. I was able to reproduce the issue twice, but I can't reproduce it consistently. I don't know what was different about the two times I got it to happen. 

If you add the debug mode, I'll try to collect more info

**Comment by franciskafieh** [comment]
That’s super odd.. I’ll try to get debug mode out ASAP. I’ve got a pretty bad flu right now though

By any chance, was SyncThing enabled on your second vault, too? I’m wondering if that could be the issue, but honestly, I can’t see how Sync would affect the output file’s location

**Comment by joh6nn** [comment]
Nope, no SyncThing 🤷

Sorry to hear about the flu, hope you feel better soon!

**Comment by franciskafieh** [comment]
Sorry for the long delay. I'm about to publish it as a pre-release, which means you will need to use the BRAT plugin or manually install it ([video here if you need help](https://www.youtube.com/watch?v=ffGfVBLDI_0)).

What you're mainly looking for is this part...
![image](https://github.com/franciskafieh/obsidian-list-modified/assets/93789670/836e7680-3eb1-44de-949d-57308e2e847d)


After you've enabled the verbose mode setting, you should be able to open the dev console as you have done before. Play around with editing files, etc, until you see a message like that or "Log note not found, but should be created automatically. Creating now..."

**Comment by franciskafieh** [comment]
Link to pre-release: https://github.com/franciskafieh/obsidian-list-modified/releases/tag/2.2.1

**Comment by joh6nn** [comment]
Ok, I made a copy of my vault, and installed 2.2.1 with BRAT:

```
plugin:obsidian-list-modified:938 OLM settings saved.
plugin:obsidian-list-modified:790 --- Writing tracked files ---
plugin:obsidian-list-modified:744 [Obsidian List Modified] Log note found at: Entries/1999/12/31.md
```

Then I created a brand new empty vault, installed only BRAT and OLM, configured Daily Note to match my real vault (as noted above), and made a Templates folder, an Entries folder, and a Notes folder. I clicked the Daily Note button in the ribbon to create a daily note from the template, and then created two files in Notes, and OLM correctly added them to today's note.

Then I created Entries/2021/09/31.md. I closed and re-opened the test vault, and created a new file in Notes, and bingo: it added the list to the incorrect note, with all 3 entries (the one from just now, and the 2 from before):

![image](https://github.com/franciskafieh/obsidian-list-modified/assets/1129329/b391947a-ba7d-42c5-abc2-49c66a631f97)

**Comment by franciskafieh** [comment]
that’s super weird.. It seems like moment.js thinks the current year is
2021, or it may be a bug in the upstream plugin I’m using to get daily
notes.. I’m gonna need to add something to the debug mode. I’ll try to get
it done within a few hours

**Comment by joh6nn** [comment]
My initial guess here is that the upstream plugin has a bug, because it also incorrectly detected 1999 as the current year, and additionally it also incorrectly detects the current month. I feel like moment.js has enough users that if it was the source of the bug, someone would have noticed :slightly_smiling_face:

**Comment by joh6nn** [comment]
Yup, confirmed: https://github.com/liamcain/obsidian-daily-notes-interface/issues/21

It's been broken for directory structures like YYYY/MM/DDD and similar for a long time, it seems.

**Comment by franciskafieh** [comment]
good detective work lol. super weird since it was working for me… since it
seems like a lot of people want it fixed but nobodys taken a shot at it, I
could try forking the plugin and figuring it out

**Comment by joh6nn** [comment]
It looks like there's actually a PR that claims to fix it: https://github.com/liamcain/obsidian-daily-notes-interface/pull/25

It's actually fixing a bug in one of the developer's other plugins (the Calendar plugin), but the underlying issue is the same.

I still haven't really wrapped my head around modern JS's functional stuff, but it looks reasonable to me? I think it's dynamically building a RegEx that matches whatever the Daily/Periodic note settings currently are, but I gladly defer to you here

**Comment by franciskafieh** [comment]
Looks good and for sure lol. Appreciate you for putting effort into the bug
too. Sorry I’m not being very helpful, on mobile rn. I’ll change the plugin
to depend on that fork and release it in a few hours. Hopefully that will
help

**Comment by joh6nn** [comment]
No worries! You've been super responsive as far as I'm concerned. Also, you're working for free; I'm grateful that you shared your work to begin with! Me putting in the legwork to make a decent bug report is the least I can do :slightly_smiling_face:

**Comment by franciskafieh** [comment]
I'll need to work on this tomorrow as adding this fork as a dependency is way harder than it should be. Sorry for the delay

**Comment by franciskafieh** [comment]
try release 2.2.2 for me on BRAT. See if that fixes it

**Comment by joh6nn** [comment]
Ok, one step forward, one step back:

Recounting all my steps in case it's relevant.

I usually leave Obsidian open in the background, so both my main vault and the from-scratch test vault were still running from the other night. I upgraded OLM in the from-scratch vault, closed it, and reopened it by clicking on the vault icon in the window for my main vault.

As expected, it automatically created a new daily, and OLM correctly identified the Daily Note! But: it incorrectly identified what files to list there: I had only just opened the vault, and not created or modified any other files, so there shouldn't have been any files to list. Instead, it listed all 3 files from the notes folder. Both Obsidian and my file browser show the last modified time as Oct 31 for all 3 files :shrug: 

![image](https://github.com/franciskafieh/obsidian-list-modified/assets/1129329/b4c1e8a6-701d-4e88-9156-3dd6f8198cdf)

**Comment by franciskafieh** [comment]
Edit: this reminds me to add some more specific things to the verbose mode

**Comment by joh6nn** [comment]
The file that was created was the the one with focus in Obsidian: 2023/11 Nov/02.md

Here's my data.json. I glanced at it real quick before uploading, and remembered: I turned off "auto create log note", which **is** reflected in the json. So either there's a bug in the verbose output and it's writing that to the console when it shouldn't, or there's a bug in the automatic file creation logic and it's running when it shouldn't
[data.json](https://github.com/franciskafieh/obsidian-list-modified/files/13242549/data.json)

**Comment by franciskafieh** [comment]
Did you edit the data.json at all? It shows no files in the trackedFiles array, so nothing should be written to your daily note... Super odd. Everything is working fine on my end (tracking the right files, note not being created automatically unless told to, etc). If there were problems with this, there would be many other issues open.

This didn't happen before the update, right? I don't see how these changes would affect any of this anyway.

Could you delete the data.json to give OLM a fresh start? Then, enable verbose mode again. Now it shows the names of created files and stuff as well. I'm honestly super confused since usually I know what I'm doing with my own plugin lol

**Comment by franciskafieh** [comment]
Oh wait, the issues with create are my fault. Verbose mode outputs "file created" even if it is not added to data.json (it's filtered out for one reason or another)

As per identifying the right files to modify, I could try adding even more test messages to see why each file is identified. But this shouldn't be necessary, and I don't know why you're getting the wrong list of files when the data.json shows no files at all.

Maybe try deleting it for now (as I said above) and see what happens

**Comment by joh6nn** [comment]
Sigh. Ok, I apologize, because I feel like I'm taking you down a rabbit hole here:

So to make sure that I hadn't unintentionally messed anything up or introduced any weirdness in the previous round of testing, I deleted my test vault and recreated it.

Like before, I was able to reproduce the issue one time, but I'm not clear on how :slightly_frowning_face:. And now I can't reproduce it again.

But while I was trying, I got OLM to insert the list of modified files to the same note twice in a single session. So naturally I wanted to see "what happens when I make a new note **now**?" and the answer was that it figured out that the list should only be added to the Log Note one time, but it deleted all the content in the note *after* the note heading :shrug:

**Comment by franciskafieh** [comment]
Don't apologize!

> and the answer was that it figured out that the list should only be added to the Log Note one time

I think it does this sometimes, but tmk it's a concurrency issue which is pretty difficult to fix without extra reads to the file and complication. As long as it solves itself, it should be fine in my books

> but it deleted all the content in the note after the note heading

this shouldn't happen. Do you think what you're describing is related to #81? I need to fix that soon anyway

**Comment by joh6nn** [comment]
Yeah, that looks like it's either the same issue, or very closely related

**Comment by franciskafieh** [comment]
#81 should be fixed now. try it out and let me know what happens :)

**Comment by franciskafieh** [comment]
Nevermind, one second

**Comment by franciskafieh** [comment]
Should be good now

**Comment by franciskafieh** [comment]
Any updates? Going to close if this issue is fixed

**Comment by joh6nn** [comment]
Hey, sorry for the radio silence, I have been crazy busy the last several weeks and haven't had time to give this the attention it deserves. I'm hoping to get to it this weekend

**Comment by franciskafieh** [comment]
No worries

**Comment by joh6nn** [comment]
so, apologies for the long delay in getting back to this

So, good news, bad news, good news.

Good news: as far as I can tell the initial issue that I opened this ticket for is fixed: in all my testing, OLM now successfully writes to the correct note.

Bad news: I'm still seeing issues with symptoms similar to #81 , where content after the insertion is being overwritten/erased. 

Good news: I can consistently reproduce it!

1. Open the vault, let Obsidian automatically create the daily note
2. manually create a new note
3. delete the daily note
4. close Obsidian, and reopen it, and let it automatically recreate the daily note
5. manually create a new note
6. et voila! everything after the inserted content is missing

Also fun: sometimes the inserted content is duplicated. Sometimes it's duplicated in its entirety, and sometimes only one or two lines are duplicated. It doesn't appear to be a rendering issue; opening a different note, and then coming back to the daily note, the duplicated content is still there. I can reproduce this frequently, but haven't figured out specific steps for reproducing it consistently. It's not clear to me whether this is related to the symptoms of #81, or if it's a separate issue

Since the original issue is now solved, do you want to move these other symptoms to a new issue (or issues?)

**Comment by franciskafieh** [comment]
Sorry, I missed the original notification. I’m still on vacation so I don’t
have access to my computer right now. I’ll try to work on this asap. Thanks
for following up

**Comment by joh6nn** [comment]
No worries, and no rush; enjoy your vacation!

**Comment by franciskafieh** [comment]
Sorry for the wait. After my break I had exams. Everything's done now, so I'm back to working on the plugin.

**Comment by joh6nn** [comment]
No worries: our lives have to come before our projects! I hope you did well on your exams 🤞

**Comment by franciskafieh** [comment]
#90 would fix this as it would be way more reliable than headings. Just want to see everyone's opinions before making the breaking change

**Comment by franciskafieh** [comment]
This has been dead for awhile, but I'm back to working on it. What's super odd is that the local "fork" of the upstream plugin that was causing the bug is exactly the same as the published version. Basically, I forgot to download the "patch" branch instead of the default. And somehow, your issue is still fixed? I'm trying to replicate it right now with the same daily note format as you, and everything seems good. Super odd. I guess I will just leave it as is for now.... I'm stumped

**Comment by franciskafieh** [comment]
Closing this for now. If it continues to happen when 3.0 comes out, please reopen
