### ISSUE TITLE
[FR] Make `Created` and `Deleted` features toggleable

### ISSUE THREAD

**Issue by joellti** [franciskafieh/obsidian-list-modified#88]
## First Steps

-   [x] I've ensured that this feature request **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified

## Describe the desired feature

Is this possible to make `Created` and `Deleted` features toggleable? I use different part of the Daily note to track created notes. To avoid the duplication, I would like the plugin to collect modified notes only, which is currently not possible.

## Possible alternatives

None

## Additional info?

None

**Comment by franciskafieh** [comment]
Do you mean you want to disable the created and deleted sections? You can
do that via the toggles in the plugin settings

**Comment by joellti** [comment]
I tried that already but it simply merges created notes with modified notes. Basically, I only want the modified notes to be there.

**Comment by franciskafieh** [comment]
I see what you mean now. Yeah, that’s currently not possible but I will
consider adding it

**Comment by joellti** [comment]
Thanks a lot for your consideration. Look forward to your next release :)

**Comment by franciskafieh** [comment]
Please take a look [here](https://github.com/franciskafieh/obsidian-list-modified/discussions/90). This could potentially fix this issue. Not adding C and D tags will mean they do not pop up in your note. If not, I would still consider it as a setting for a future release.

**Comment by franciskafieh** [comment]
Fixed in 3.0! Please see https://github.com/franciskafieh/obsidian-list-modified/releases/tag/3.0.0-alpha for release info and alpha installation instructions.
