### ISSUE TITLE
[BUG] File rename corrupts OLM data when "Automatically update internal links" is disabled

### ISSUE THREAD

**Issue by cotneit** [franciskafieh/obsidian-list-modified#93]
## First Steps

-   [x] I've ensured that the issue **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified
-   [x] I've tried disabling any other plugins that may cause conflicts (recommended)

## Describe the bug

Renaming a file with "Automatically update internal links" disabled messes up the data written by OLM to daily note after renamed link. See repro section for more details.

Not an issue for files that have multiple links because after renaming a file, files that link to it are also modified, looks like it writes corrupted data on rename but then overrides with good data when files that link to the renamed file are modified.

Since modifying any file fixes the link in OLM, this is pretty much only an issue when triggered at the end of the day.

## Expected behaviour

Shouldn't happen

### My setup

-   **What device are you on?** - Windows 11, Obsidian v1.5.12
-   \*\*What sync service are you using? (if relevant to bug) - None

### Steps to reproduce bug

Can you pinpoint when/why this bug happens?

1. Settings => Files and links => Disable "Automatically update internal links"
2. Make sure either "Linked mentions" view is visible (not needed for repro but will help with understanding the problem)
3. Create a new file OR Modify a file that has no links to it except the one in current daily note generated by OLM
4. Rename the file so that filename length is different. When prompted with "Update links", don't click anything just yet
5. Pay attention to "Linked mentions" view, at this point the link in daily note is renamed
6. Click "Just once" when prompted with "Do you want to update internal links that link to this file?"
7. Now the link in daily note is a bit messed up.

**Comment by franciskafieh** [comment]
Thanks for the super detailed bug report.

> Since modifying any file fixes the link in OLM, this is pretty much only an issue when triggered at the end of the day.

Unless I am misunderstanding, the same logic when a file is modified is also ran at the end of a day, so it is odd that editing a file would fix this. I will look more into it when I have time, though

**Comment by franciskafieh** [comment]
@cotneit do you by chance have an interval set? in the plugin's data.json, there should be a `writeInterval` field. What does this number read?

**Comment by cotneit** [comment]
@franciskafieh  `writeInterval` is set to 0

> Unless I am misunderstanding, the same logic when a file is modified is also ran at the end of a day, so it is odd that editing a file would fix this. I will look more into it when I have time, though

Sorry, this being an issue at the end of the day was likely an assumption on my part, I don't think I actually tested that, I just noticed that a couple of my older daily notes looked weird so I assumed that's what happened.

**Comment by franciskafieh** [comment]
I will look into it when I have time, thank you for the update. Will be fixed before 3.0

**Comment by cotneit** [comment]
Thank you!

And btw I tested the case where I rename a note at the end of the day and come back a few days later and indeed the "old" daily note stays broken

**Comment by franciskafieh** [comment]
will be fixed in next release. The fix I used is a simple workaround that does not update the log note automatically on rename if you have auto update links turned off. This was causing Obsidian and the plugin to basically fight to rename the file
