### ISSUE TITLE
[FR] Ability to list individual edits

### ISSUE THREAD

**Issue by alex-calderwood** [franciskafieh/obsidian-list-modified#95]
## First Steps

-   [x] I've ensured that this feature request **does not already exist** by [using the search issues feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified

## Describe the desired feature

I would like to list the individual lines that are edited so I can see a comprehensive view of what I did that day. That's why I got the app in the first place, but it doesn't do that. I don't know how big of a lift / extension the idea would be. 

## Possible alternatives

Rather than listing lines, you could also list the sections that have been changed and/or highlight them in some way?

**Comment by franciskafieh** [comment]
Hi there. Thank you for the feature request.

> I would like to list the individual lines that are edited so I can see a comprehensive view of what I did that day

This is out of the scope of this plugin, as it would require a lot more processing of every change done. There are definitely other plugins and systems you may want to look at. Off the top of my head, I would recommend [Obsidian Git](https://github.com/denolehov/obsidian-git)

**Comment by franciskafieh** [comment]
Closing for now, but if you have any more questions, feel free to re-open
