### ISSUE TITLE
[BUG] Trying to install it on mobile (iOS) return “impossible to install…”

### ISSUE THREAD

**Issue by Azmoinal** [franciskafieh/obsidian-list-modified#97]
I’m using obsidian 1.7 and I would try your plugin but if I try to install it from community plugin list, installation fails with a message “impossibile to install the plugin: List Modified”.

I noticed that the version reported into obsidian is 3.0.0 while it should available only on BRAT (as it seems from GitHub).

**Comment by dmnkf** [comment]
I am not sure if you mean MacOS or iOS but either way MacOS is also affected.

**Comment by Azmoinal** [comment]
My fault, I was speaking about iOS but in an edit of text I removed the sentence.

**Comment by franciskafieh** [comment]
Thanks both of you for letting me know. I will look into it asap

**Comment by franciskafieh** [comment]
Should be fixed now. Let me know if it's not.

**Comment by Azmoinal** [comment]
It works. At least on iOS, I cannot check macOS right now.

**Comment by franciskafieh** [comment]
Thanks. It should be fixed on all platforms then. If you like v2, feel free to check out v3 with BRAT
