### ISSUE TITLE
[FR] Table Support

### ISSUE THREAD

**Issue by TrulyFlawed** [franciskafieh/obsidian-list-modified#98]
## First Steps

-   [x] I've ensured that this feature request **does not already exist** by [using the search feature](https://github.com/franciskafieh/obsidian-list-modified/issues?q=search+issues+here)
-   [x] I've read the documentation (see [the README](https://github.com/franciskafieh/obsidian-list-modified#readme))
-   [x] I'm on the latest release of obsidian-list-modified

## Describe the desired feature

I'd like the see the option for the plugin to generate the list of modified/created/deleted notes into a table instead of a list, as parsing information such as the created or modified dates are easier for me to do on a table since the length of each "column" doesn't vary as much as when presented as a list.

## Possible alternatives

What are some possible alternatives? Have you tried any of them?

I've tried messing around with trying to get the table syntax to work with both the latest stable release and the pre-release v3.0.0 and I couldn't get either to update the tables properly after attempting to set them up.

With v2.2.3 the issue preventing me from making tables was that the table header kept getting removed.
With v3.0.0 I tried to place the table header outside of the divider, but all this did was stop the plugin from working. I haven't tried putting the header inside of the dividers but I'm figuring it'll just remove them.

## Additional info?

Not to my knowledge, no.

**Comment by franciskafieh** [comment]
> I tried to place the table header outside of the divider, but all this did was stop the plugin from working.

This should not happen. Can you send a screenshot of your note when you do this?

> I haven't tried putting the header inside of the dividers but I'm figuring it'll just remove them.

Correct

**Comment by TrulyFlawed** [comment]
I think I may have been wrong there, the plugin still works just fine when I place a table header outside of the divider, the problem earlier was that I was including the dividers inside of the table itself (which in hindsight might have been way more useful for information).

Otherwise, I've just tested only the table header outside and the plugin works fine, but there's still the case of tables not being able to properly show up even with the header. If you want any screenshots still I can do that, I made a quick vault just now to test this since I just went back to the old version and have accepted using lists for the time being.

**Comment by franciskafieh** [comment]
Have you tried something like this on 3.0.0?

```

| Name | Tags |
| --------- | -------- |
%% LIST MODIFIED%%
%% END
```

and set your output format to something like `| [[name]] | [[tags]] |`

This won't work right away, but when the %% comments are removed at the end of each day, it should format into a table

**Comment by TrulyFlawed** [comment]
Oh okay! I didn't realize the dividers would disappear after the end of each day. That helps a lot, thanks. I guess I missed that part when reading the wiki.

Admittedly I wish it could look nicer as a table without having to wait for the next day but I'll take this over absolutely no hope in achieving table support. Thank you for the help!

**Comment by franciskafieh** [comment]
> Admittedly I wish it could look nicer as a table without having to wait for the next day but I'll take this over absolutely no hope in achieving table support.

If anyone else would like this to be possible, please re-open the issue and leave a comment. It would not be super easy to implement but I could do it if there is enough demand

**Comment by technotherion** [comment]
My only insight on this is that there could  be a command that automatically generates a table from the existing List Modified headers/tables/etc and then 'locks' it so that it can no longer by edited by the plugin. This still seems like it would be an 'end of day' or 'day after' thing, however, and I'm not sure if it's necessary since other plugins could do the same thing,
