### ISSUE TITLE
[FR] Different output format for different sections

### ISSUE THREAD

**Issue by technotherion** [franciskafieh/obsidian-list-modified#99]
List Modified 2.2.3

In my settings for this plugin, I have `- [[link]] [[ctime]]` as my output format. This works great for the Created section, but not as great for the Modified section, where i'd rather see mtime instead.

I understand that this information would be pretty self-explanatory if placed within a Daily Note, but this is placed within my Weekly Note where I'd like to see what day I've created or modified a note on.

**Comment by franciskafieh** [comment]
Might as well implement a feature to have a separate format for each heading, would also fix #100

**Comment by franciskafieh** [comment]
TODO (for myself) before next release:
- add frontmatter templates to output wiki
- integrated testing with new deleted notes format logic and also separate formatting logic

**Comment by franciskafieh** [comment]
Done in release [3.1.0-alpha](https://github.com/franciskafieh/obsidian-list-modified/releases/tag/3.1.0-alpha)
